object TurnDBF: TTurnDBF
  Left = 192
  Top = 107
  Width = 435
  Height = 300
  Caption = 'TurnDBF'
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = False
  PixelsPerInch = 96
  TextHeight = 13
  object Button1: TButton
    Left = 128
    Top = 232
    Width = 75
    Height = 25
    Caption = 'Button1'
    TabOrder = 0
  end
end
