object RestForm: TRestForm
  Left = 159
  Top = 195
  Width = 426
  Height = 220
  BorderIcons = []
  Caption = '程序注册窗口'
  Color = clBtnFace
  Font.Charset = GB2312_CHARSET
  Font.Color = clWindowText
  Font.Height = -15
  Font.Name = '宋体'
  Font.Style = []
  OldCreateOrder = False
  Position = poScreenCenter
  OnCreate = FormCreate
  PixelsPerInch = 96
  TextHeight = 15
  object Label1: TLabel
    Left = 75
    Top = 38
    Width = 106
    Height = 15
    Caption = '&S-注册提示码：'
    FocusControl = Edit1
    Font.Charset = GB2312_CHARSET
    Font.Color = clBlue
    Font.Height = -15
    Font.Name = '宋体'
    Font.Style = []
    ParentFont = False
  end
  object Label2: TLabel
    Left = 75
    Top = 84
    Width = 106
    Height = 15
    Caption = '&C-输入注册码：'
    FocusControl = Edit2
    Font.Charset = GB2312_CHARSET
    Font.Color = clBlue
    Font.Height = -15
    Font.Name = '宋体'
    Font.Style = []
    ParentFont = False
  end
  object Edit1: TEdit
    Left = 179
    Top = 34
    Width = 165
    Height = 23
    Font.Charset = GB2312_CHARSET
    Font.Color = clBlue
    Font.Height = -15
    Font.Name = '宋体'
    Font.Style = []
    ParentFont = False
    ReadOnly = True
    TabOrder = 1
  end
  object Edit2: TEdit
    Left = 179
    Top = 80
    Width = 165
    Height = 23
    Font.Charset = GB2312_CHARSET
    Font.Color = clBlue
    Font.Height = -15
    Font.Name = '宋体'
    Font.Style = []
    ParentFont = False
    TabOrder = 0
  end
  object Button1: TButton
    Left = 54
    Top = 134
    Width = 135
    Height = 25
    Caption = '注册(&R)'
    Default = True
    ModalResult = 1
    TabOrder = 2
    OnClick = Button1Click
  end
  object Button2: TButton
    Left = 230
    Top = 134
    Width = 135
    Height = 25
    Cancel = True
    Caption = '退出(&X)'
    ModalResult = 2
    TabOrder = 3
    OnClick = Button2Click
  end
end
