/* SET SQL DIALECT 3; */

/* CREATE DATABASE 'D:\LFSOFTHOTEL\DATABASE\USERDATA\HOTELDATA.GDB' PAGE_SIZE 4096

 DEFAULT CHARACTER SET  */
/* Domain definitions */
CREATE DOMAIN "DOMAIN_BH" AS VARCHAR(5);
CREATE DOMAIN "DOMAIN_BZ" AS VARCHAR(30);
CREATE DOMAIN "DOMAIN_C10" AS VARCHAR(10);
CREATE DOMAIN "DOMAIN_C12" AS VARCHAR(12);
CREATE DOMAIN "DOMAIN_C16" AS VARCHAR(16);
CREATE DOMAIN "DOMAIN_C18" AS VARCHAR(18);
CREATE DOMAIN "DOMAIN_C2" AS VARCHAR(2);
CREATE DOMAIN "DOMAIN_C20" AS VARCHAR(20);
CREATE DOMAIN "DOMAIN_C4" AS VARCHAR(4);
CREATE DOMAIN "DOMAIN_C6" AS VARCHAR(6);
CREATE DOMAIN "DOMAIN_C7" AS VARCHAR(7);
CREATE DOMAIN "DOMAIN_C8" AS VARCHAR(8);
CREATE DOMAIN "DOMAIN_CURRENCY" AS FLOAT
	 DEFAULT 0;
CREATE DOMAIN "DOMAIN_DATETIME" AS TIMESTAMP;
CREATE DOMAIN "DOMAIN_DM" AS VARCHAR(10);
CREATE DOMAIN "DOMAIN_FS" AS VARCHAR(10);
CREATE DOMAIN "DOMAIN_LOGIC" AS CHAR(1)
	 DEFAULT 'F';
CREATE DOMAIN "DOMAIN_LXM" AS VARCHAR(30);
CREATE DOMAIN "DOMAIN_MC" AS VARCHAR(10);
CREATE DOMAIN "DOMAIN_MEMO" AS BLOB SUB_TYPE 0 SEGMENT SIZE 80;
CREATE DOMAIN "DOMAIN_SJ" AS CHAR(4);
CREATE DOMAIN "DOMAIN_SL" AS INTEGER
	 DEFAULT 0;
CREATE DOMAIN "DOMAIN_SLF" AS FLOAT
	 DEFAULT 0;
CREATE DOMAIN "DOMAIN_USEBH" AS VARCHAR(12);
CREATE DOMAIN "DOMAIN_XM" AS VARCHAR(8);
CREATE DOMAIN "DOMAIN_ZT" AS CHAR(1);

/* Table: BASICFMT, Owner: SYSDBA */

CREATE TABLE "BASICFMT" 
(
  "CLASS"	"DOMAIN_BH",
  "SDATE"	"DOMAIN_C8",
  "STIME"	"DOMAIN_BH",
  "LAST"	"DOMAIN_SLF",
  "NUMBER"	"DOMAIN_C16"
);

/* Table: BH, Owner: SYSDBA */

CREATE TABLE "BH" 
(
  "D_YDBH"	"DOMAIN_USEBH",
  "D_YJBH"	"DOMAIN_USEBH",
  "D_KRBH"	"DOMAIN_USEBH",
  "D_ZDBH"	"DOMAIN_USEBH",
  "D_JZBH"	"DOMAIN_USEBH",
  "D_DCBH"	"DOMAIN_USEBH"
);

/* Table: BMDM, Owner: SYSDBA */

CREATE TABLE "BMDM" 
(
  "D_BMBH"	"DOMAIN_BH" NOT NULL,
  "D_BMMC"	"DOMAIN_MC" NOT NULL,
  "D_DM"	"DOMAIN_DM",
CONSTRAINT "D_BMDM" PRIMARY KEY ("D_BMBH")
);

/* Table: BQJ, Owner: SYSDBA */

CREATE TABLE "BQJ" 
(
  "D_KFBH"	"DOMAIN_BH" NOT NULL,
  "D_SJFJ"	"DOMAIN_CURRENCY",
  "D_BJS"	"DOMAIN_SL",
  "D_QJS"	"DOMAIN_SL",
  "D_BJ"	"DOMAIN_BZ",
  "D_QJ"	"DOMAIN_BZ",
  "D_JJFJ"	"DOMAIN_CURRENCY",
CONSTRAINT "D_BQJ" PRIMARY KEY ("D_KFBH")
);

/* Table: CARD, Owner: SYSDBA */

CREATE TABLE "CARD" 
(
  "D_CARDID"	"DOMAIN_C6" NOT NULL,
  "D_KRXM"	"DOMAIN_XM" NOT NULL,
  "D_ZJHM"	"DOMAIN_C18",
  "D_ZE"	"DOMAIN_CURRENCY"  DEFAULT 0,
  "D_JE"	"DOMAIN_CURRENCY"  DEFAULT 0,
  "D_YE"	"DOMAIN_CURRENCY"  DEFAULT 0,
  "D_XKR"	"DOMAIN_XM",
  "D_XKRQ"	"DOMAIN_DATETIME",
  "D_XKSJ"	"DOMAIN_DATETIME",
CONSTRAINT "D_CARDID" PRIMARY KEY ("D_CARDID")
);

/* Table: CARDXF, Owner: SYSDBA */

CREATE TABLE "CARDXF" 
(
  "D_CARDID"	"DOMAIN_C6" NOT NULL,
  "D_KRXM"	"DOMAIN_XM" NOT NULL,
  "D_XFJE"	"DOMAIN_CURRENCY"  DEFAULT 0,
  "D_XFRQ"	"DOMAIN_DATETIME",
  "D_XFSJ"	"DOMAIN_DATETIME",
  "D_CZYXM"	"DOMAIN_XM"
);

/* Table: CDDM, Owner: SYSDBA */

CREATE TABLE "CDDM" 
(
  "D_CDBH"	"DOMAIN_BH" NOT NULL,
  "D_MJ"	"DOMAIN_ZT",
  "D_CDMC"	"DOMAIN_C20",
  "D_XMBH"	"DOMAIN_BH",
  "D_DJ1"	"DOMAIN_CURRENCY",
  "D_DJ2"	"DOMAIN_CURRENCY",
  "D_DJ3"	"DOMAIN_CURRENCY",
  "D_DM"	"DOMAIN_DM",
  "D_BZ"	"DOMAIN_BZ",
CONSTRAINT "D_CDDM" PRIMARY KEY ("D_CDBH")
);

/* Table: CTDC, Owner: SYSDBA */

CREATE TABLE "CTDC" 
(
  "D_DCBH"	"DOMAIN_USEBH" NOT NULL,
  "D_CTBH"	"DOMAIN_BH" NOT NULL,
  "D_XMBH"	"DOMAIN_BH" NOT NULL,
  "D_DCLB"	"DOMAIN_ZT",
  "D_XFRQ"	"DOMAIN_DATETIME",
  "D_XFSJ"	"DOMAIN_DATETIME",
  "D_SJDM"	"DOMAIN_SJ",
  "D_KRSL"	"DOMAIN_SL",
  "D_YCBZ"	"DOMAIN_BZ",
  "D_KRXM"	"DOMAIN_LXM",
  "D_JSBZ"	"DOMAIN_ZT",
  "D_JZFS"	"DOMAIN_FS",
  "D_KHBH"	"DOMAIN_BH",
  "D_XYKBH"	"DOMAIN_BH",
  "D_XFJE"	"DOMAIN_CURRENCY",
  "D_YHJE"	"DOMAIN_CURRENCY",
  "D_CZYXM"	"DOMAIN_XM",
  "D_YDBH"	"DOMAIN_USEBH",
  "D_BZ"	"DOMAIN_BZ",
CONSTRAINT "D_CTDC" PRIMARY KEY ("D_DCBH", "D_CTBH", "D_XMBH")
);

/* Table: CTDCDA, Owner: SYSDBA */

CREATE TABLE "CTDCDA" 
(
  "D_DCBH"	"DOMAIN_USEBH" NOT NULL,
  "D_CTBH"	"DOMAIN_BH" NOT NULL,
  "D_XMBH"	"DOMAIN_BH" NOT NULL,
  "D_DCLB"	"DOMAIN_ZT",
  "D_XFRQ"	"DOMAIN_DATETIME",
  "D_XFSJ"	"DOMAIN_DATETIME",
  "D_SJDM"	"DOMAIN_SJ",
  "D_KRSL"	"DOMAIN_SL",
  "D_YCBZ"	"DOMAIN_BZ",
  "D_KRXM"	"DOMAIN_LXM",
  "D_JSBZ"	"DOMAIN_ZT",
  "D_JZFS"	"DOMAIN_FS",
  "D_KHBH"	"DOMAIN_BH",
  "D_XYKBH"	"DOMAIN_BH",
  "D_XFJE"	"DOMAIN_CURRENCY",
  "D_YHJE"	"DOMAIN_CURRENCY",
  "D_CZYXM"	"DOMAIN_XM",
  "D_YDBH"	"DOMAIN_USEBH",
  "D_BZ"	"DOMAIN_BZ",
CONSTRAINT "CTDC1D_CTDC" PRIMARY KEY ("D_DCBH", "D_CTBH", "D_XMBH")
);

/* Table: CTDM, Owner: SYSDBA */

CREATE TABLE "CTDM" 
(
  "D_CTBH"	"DOMAIN_BH" NOT NULL,
  "D_CTLB"	"DOMAIN_C4" NOT NULL,
  "D_CTMC"	"DOMAIN_MC" NOT NULL,
  "D_DM"	"DOMAIN_DM",
CONSTRAINT "D_CTDM" PRIMARY KEY ("D_CTBH")
);

/* Table: CTJZ, Owner: SYSDBA */

CREATE TABLE "CTJZ" 
(
  "D_XMBH"	"DOMAIN_BH",
  "D_XFJE"	"DOMAIN_CURRENCY",
  "D_YHJE"	"DOMAIN_CURRENCY",
  "D_BZ"	"DOMAIN_LOGIC"
);

/* Table: CTXM, Owner: SYSDBA */

CREATE TABLE "CTXM" 
(
  "D_XMBH"	"DOMAIN_BH" NOT NULL,
  "D_XMMC"	"DOMAIN_MC" NOT NULL,
  "D_DM"	"DOMAIN_DM",
CONSTRAINT "D_CTXM" PRIMARY KEY ("D_XMBH")
);

/* Table: CTZT, Owner: SYSDBA */

CREATE TABLE "CTZT" 
(
  "D_CTBH"	"DOMAIN_BH" NOT NULL,
  "D_CTMC"	"DOMAIN_MC" NOT NULL,
  "D_CTZT"	"DOMAIN_ZT" NOT NULL,
  "D_DCBH"	"DOMAIN_USEBH",
  "D_KRXM"	"DOMAIN_LXM",
  "D_KRSL"	"DOMAIN_SL",
  "D_XFRQ"	"DOMAIN_DATETIME",
  "D_XFSJ"	"DOMAIN_DATETIME",
  "D_JZRQ"	"DOMAIN_DATETIME",
  "D_JZSJ"	"DOMAIN_DATETIME",
CONSTRAINT "D_CTBH" PRIMARY KEY ("D_CTBH")
);

/* Table: CWJS, Owner: SYSDBA */

CREATE TABLE "CWJS" 
(
  "D_YSRQ"	"DOMAIN_C8",
  "D_JSLX"	"DOMAIN_ZT",
  "D_RMB"	"DOMAIN_CURRENCY",
  "D_XYK"	"DOMAIN_CURRENCY",
  "D_ZP"	"DOMAIN_CURRENCY",
  "D_CZYXM"	"DOMAIN_XM",
  "D_LRRQ"	"DOMAIN_DATETIME",
  "D_LRSJ"	"DOMAIN_DATETIME"
);

/* Table: CZXM, Owner: SYSDBA */

CREATE TABLE "CZXM" 
(
  "D_CZBH"	"DOMAIN_BH" NOT NULL,
  "D_CZXM"	"DOMAIN_C20",
CONSTRAINT "D_CZXM" PRIMARY KEY ("D_CZBH")
);

/* Table: DCMX, Owner: SYSDBA */

CREATE TABLE "DCMX" 
(
  "D_DCBH"	"DOMAIN_USEBH" NOT NULL,
  "D_CTBH"	"DOMAIN_BH" NOT NULL,
  "D_CDBH"	"DOMAIN_BH" NOT NULL,
  "D_XMBH"	"DOMAIN_BH",
  "D_CDMC"	"DOMAIN_C20",
  "D_XFSL"	"DOMAIN_SLF",
  "D_THSL"	"DOMAIN_SLF",
  "D_DJ"	"DOMAIN_CURRENCY",
  "D_XFRQ"	"DOMAIN_DATETIME",
  "D_DEL"	"DOMAIN_LOGIC",
  "D_BZ"	"DOMAIN_BZ",
CONSTRAINT "D_DCMX" PRIMARY KEY ("D_DCBH", "D_CTBH", "D_CDBH")
);

/* Table: DCMXDA, Owner: SYSDBA */

CREATE TABLE "DCMXDA" 
(
  "D_DCBH"	"DOMAIN_USEBH" NOT NULL,
  "D_CTBH"	"DOMAIN_BH" NOT NULL,
  "D_CDBH"	"DOMAIN_BH" NOT NULL,
  "D_XMBH"	"DOMAIN_BH",
  "D_CDMC"	"DOMAIN_C20",
  "D_XFSL"	"DOMAIN_SLF",
  "D_THSL"	"DOMAIN_SLF",
  "D_DJ"	"DOMAIN_CURRENCY",
  "D_XFRQ"	"DOMAIN_DATETIME",
  "D_DEL"	"DOMAIN_LOGIC",
  "D_BZ"	"DOMAIN_BZ",
CONSTRAINT "DCMX1D_DCMX" PRIMARY KEY ("D_DCBH", "D_CTBH", "D_CDBH")
);

/* Table: DHF, Owner: SYSDBA */

CREATE TABLE "DHF" 
(
  "CLASS"	"DOMAIN_BH",
  "ROOM"	"DOMAIN_BH",
  "PLACE"	"DOMAIN_C12",
  "NUMBER"	"DOMAIN_C16",
  "SDATE"	"DOMAIN_C8",
  "STIME"	"DOMAIN_C6",
  "LAST"	"DOMAIN_SLF",
  "UNIT"	"DOMAIN_CURRENCY",
  "FEE"	"DOMAIN_CURRENCY",
  "ADDI_FEE"	"DOMAIN_CURRENCY",
  "SVC_FEE"	"DOMAIN_CURRENCY",
  "TOTAL"	"DOMAIN_CURRENCY",
  "FLTY"	"DOMAIN_SL"
);

/* Table: DHHM, Owner: SYSDBA */

CREATE TABLE "DHHM" 
(
  "D_DWMC"	"DOMAIN_BZ",
  "D_DHHM"	"DOMAIN_BZ",
  "D_BZ"	"DOMAIN_BZ"
);

/* Table: DQDM, Owner: SYSDBA */

CREATE TABLE "DQDM" 
(
  "D_DQBH"	"DOMAIN_BH" NOT NULL,
  "D_DQMC"	"DOMAIN_MC" NOT NULL,
  "D_DM"	"DOMAIN_DM",
CONSTRAINT "D_DQDM" PRIMARY KEY ("D_DQBH")
);

/* Table: EWF, Owner: SYSDBA */

CREATE TABLE "EWF" 
(
  "D_JZBH"	"DOMAIN_USEBH" NOT NULL,
  "D_KRXM"	"DOMAIN_LXM",
  "D_EWF"	"DOMAIN_CURRENCY",
  "D_JZRQ"	"DOMAIN_DATETIME",
  "D_JZSJ"	"DOMAIN_DATETIME",
  "D_YSRQ"	"DOMAIN_C8",
CONSTRAINT "D_EWF" PRIMARY KEY ("D_JZBH")
);

/* Table: FARE, Owner: SYSDBA */

CREATE TABLE "FARE" 
(
  "PLACE"	"DOMAIN_C20",
  "CODE"	"DOMAIN_C7",
  "UNIT"	"DOMAIN_CURRENCY",
  "ABBR"	"DOMAIN_C6"
);

/* Table: FLDM, Owner: SYSDBA */

CREATE TABLE "FLDM" 
(
  "D_FLBH"	"DOMAIN_BH" NOT NULL,
  "D_FLMC"	"DOMAIN_MC" NOT NULL,
  "D_DM"	"DOMAIN_DM",
CONSTRAINT "D_FLDM" PRIMARY KEY ("D_FLBH")
);

/* Table: FXDM, Owner: SYSDBA */

CREATE TABLE "FXDM" 
(
  "D_FXBH"	"DOMAIN_BH" NOT NULL,
  "D_FXMC"	"DOMAIN_MC" NOT NULL,
  "D_DM"	"DOMAIN_DM",
CONSTRAINT "D_FXDM" PRIMARY KEY ("D_FXBH")
);

/* Table: GBDM, Owner: SYSDBA */

CREATE TABLE "GBDM" 
(
  "D_GBBH"	"DOMAIN_BH" NOT NULL,
  "D_GBMC"	"DOMAIN_MC" NOT NULL,
  "D_DM"	"DOMAIN_DM",
CONSTRAINT "D_GBDM" PRIMARY KEY ("D_GBBH")
);

/* Table: HBSK, Owner: SYSDBA */

CREATE TABLE "HBSK" 
(
  "D_HBBC"	"DOMAIN_DM",
  "D_HH"	"DOMAIN_SL",
  "D_KJLX"	"DOMAIN_C20",
  "D_SFZ"	"DOMAIN_DM",
  "D_ZDZ"	"DOMAIN_DM",
  "D_SFSJ"	"DOMAIN_DATETIME",
  "D_ZDSJ"	"DOMAIN_DATETIME",
  "D_ZJZ"	"DOMAIN_DM",
  "D_DZSJ"	"DOMAIN_DATETIME"
);

/* Table: HCDM, Owner: SYSDBA */

CREATE TABLE "HCDM" 
(
  "D_HCBH"	"DOMAIN_BH" NOT NULL,
  "D_HCMC"	"DOMAIN_MC" NOT NULL,
  "D_DM"	"DOMAIN_DM",
CONSTRAINT "D_HCDM" PRIMARY KEY ("D_HCBH")
);

/* Table: HMD, Owner: SYSDBA */

CREATE TABLE "HMD" 
(
  "D_XM"	"DOMAIN_XM" NOT NULL,
  "D_ZJHM"	"DOMAIN_C18" NOT NULL,
  "D_NL"	"DOMAIN_SL",
  "D_LRRQ"	"DOMAIN_DATETIME",
  "D_JTDZ"	"DOMAIN_BZ",
  "D_BZ"	"DOMAIN_BZ",
CONSTRAINT "D_HMD" PRIMARY KEY ("D_XM", "D_ZJHM")
);

/* Table: HOLIDAY, Owner: SYSDBA */

CREATE TABLE "HOLIDAY" 
(
  "HOLIDAY"	"DOMAIN_DATETIME",
  "FTIME"	"DOMAIN_DATETIME",
  "STIME"	"DOMAIN_DATETIME"
);

/* Table: JFCONFIG, Owner: SYSDBA */

CREATE TABLE "JFCONFIG" 
(
  "MANAGE"	"DOMAIN_SL",
  "SUNDAY"	"DOMAIN_LOGIC",
  "FTIME"	"DOMAIN_DATETIME",
  "STIME"	"DOMAIN_DATETIME",
  "SHJF"	"DOMAIN_LOGIC",
  "SHPT"	"DOMAIN_LOGIC",
  "ADDIFEE"	"DOMAIN_CURRENCY",
  "ADDIFEE0"	"DOMAIN_CURRENCY",
  "XXTF"	"DOMAIN_CURRENCY",
  "SVC"	"DOMAIN_SLF",
  "SVC0"	"DOMAIN_CURRENCY",
  "GJ"	"DOMAIN_CURRENCY",
  "GN"	"DOMAIN_CURRENCY",
  "NH"	"DOMAIN_CURRENCY",
  "WXF"	"DOMAIN_CURRENCY",
  "YZF"	"DOMAIN_CURRENCY",
  "SHFEE"	"DOMAIN_CURRENCY",
  "SHUNIT"	"DOMAIN_SLF",
  "SHFEE0"	"DOMAIN_CURRENCY",
  "SHUNIT0"	"DOMAIN_SLF",
  "NHFEE"	"DOMAIN_CURRENCY",
  "NHUNIT"	"DOMAIN_SLF",
  "GNFEE"	"DOMAIN_CURRENCY",
  "GNUNIT"	"DOMAIN_SLF",
  "GJFEE"	"DOMAIN_CURRENCY",
  "GJUNIT"	"DOMAIN_SLF",
  "GATFEE"	"DOMAIN_CURRENCY",
  "GATUNIT"	"DOMAIN_SLF",
  "GNFEEYH"	"DOMAIN_CURRENCY",
  "GNYHUNIT"	"DOMAIN_SLF",
  "GJFEEYH"	"DOMAIN_CURRENCY",
  "GJYHUNIT"	"DOMAIN_SLF"
);

/* Table: JZFLTJ, Owner: SYSDBA */

CREATE TABLE "JZFLTJ" 
(
  "D_YSRQ"	"DOMAIN_C8" NOT NULL,
  "D_JZFS"	"DOMAIN_FS" NOT NULL,
  "D_XMBH"	"DOMAIN_BH" NOT NULL,
  "D_SH"	"DOMAIN_CURRENCY",
  "D_YH"	"DOMAIN_CURRENCY",
CONSTRAINT "D_JZFLTJ" PRIMARY KEY ("D_YSRQ", "D_JZFS", "D_XMBH")
);

/* Table: KFDM, Owner: SYSDBA */

CREATE TABLE "KFDM" 
(
  "D_KFBH"	"DOMAIN_BH" NOT NULL,
  "D_KFMC"	"DOMAIN_MC" NOT NULL,
  "D_BZFJ"	"DOMAIN_CURRENCY" NOT NULL,
  "D_FXBH"	"DOMAIN_BH" NOT NULL,
  "D_LCBH"	"DOMAIN_BH" NOT NULL,
  "D_CWS"	"DOMAIN_SL" NOT NULL,
CONSTRAINT "D_KFDM" PRIMARY KEY ("D_KFBH")
);

/* Table: KFZT, Owner: SYSDBA */

CREATE TABLE "KFZT" 
(
  "D_KFBH"	"DOMAIN_BH" NOT NULL,
  "D_ZDBH"	"DOMAIN_USEBH",
  "D_KRBH"	"DOMAIN_USEBH",
  "D_YJBH"	"DOMAIN_USEBH",
  "D_SJFJ"	"DOMAIN_CURRENCY",
  "D_KFZT"	"DOMAIN_ZT",
  "D_KFBZ"	"DOMAIN_ZT",
  "D_KRSL"	"DOMAIN_SL",
  "D_DHKT"	"DOMAIN_LOGIC",
  "D_BZFJ"	"DOMAIN_CURRENCY",
  "D_CWS"	"DOMAIN_SL",
  "D_BJS"	"DOMAIN_SL",
  "D_QJS"	"DOMAIN_SL",
  "D_JJFJ"	"DOMAIN_CURRENCY",
  "D_FXBH"	"DOMAIN_BH",
  "D_LCBH"	"DOMAIN_BH",
  "D_KRXM"	"DOMAIN_LXM",
CONSTRAINT "D_KFZT" PRIMARY KEY ("D_KFBH")
);

/* Table: KHDA, Owner: SYSDBA */

CREATE TABLE "KHDA" 
(
  "D_KHBH"	"DOMAIN_BH" NOT NULL,
  "D_KHMC"	"DOMAIN_LXM" NOT NULL,
  "D_FLBH"	"DOMAIN_BH" NOT NULL,
  "D_DWDZ"	"DOMAIN_BZ",
  "D_FR"	"DOMAIN_XM",
  "D_LXDH"	"DOMAIN_C16",
  "D_JDRQ"	"DOMAIN_DATETIME",
  "D_DM"	"DOMAIN_DM",
CONSTRAINT "D_KHDA" PRIMARY KEY ("D_KHBH")
);

/* Table: KRJZ, Owner: SYSDBA */

CREATE TABLE "KRJZ" 
(
  "D_JZBH"	"DOMAIN_USEBH" NOT NULL,
  "D_HH"	"DOMAIN_SL" NOT NULL,
  "D_XMBH"	"DOMAIN_BH",
  "D_XFDJ"	"DOMAIN_CURRENCY",
  "D_XFSL"	"DOMAIN_SLF",
  "D_XFGG"	"DOMAIN_BH",
  "D_XFJE"	"DOMAIN_CURRENCY",
  "D_YJJE"	"DOMAIN_CURRENCY",
  "D_YHJE"	"DOMAIN_CURRENCY",
  "D_JZFS"	"DOMAIN_FS",
  "D_JZLX"	"DOMAIN_ZT",
  "D_KHBH"	"DOMAIN_BH",
  "D_XYKBH"	"DOMAIN_BH",
  "D_JZRQ"	"DOMAIN_DATETIME",
  "D_JZSJ"	"DOMAIN_DATETIME",
  "D_CZYXM"	"DOMAIN_XM",
  "D_BZ"	"DOMAIN_BZ",
  "D_YSRQ"	"DOMAIN_C8",
CONSTRAINT "D_KRJZ" PRIMARY KEY ("D_JZBH", "D_HH")
);

/* Table: KRJZDA, Owner: SYSDBA */

CREATE TABLE "KRJZDA" 
(
  "D_JZBH"	"DOMAIN_USEBH" NOT NULL,
  "D_HH"	"DOMAIN_SL" NOT NULL,
  "D_XMBH"	"DOMAIN_BH",
  "D_XFDJ"	"DOMAIN_CURRENCY",
  "D_XFSL"	"DOMAIN_SLF",
  "D_XFGG"	"DOMAIN_BH",
  "D_XFJE"	"DOMAIN_CURRENCY",
  "D_YJJE"	"DOMAIN_CURRENCY",
  "D_YHJE"	"DOMAIN_CURRENCY",
  "D_JZFS"	"DOMAIN_FS",
  "D_JZLX"	"DOMAIN_ZT",
  "D_KHBH"	"DOMAIN_BH",
  "D_XYKBH"	"DOMAIN_BH",
  "D_JZRQ"	"DOMAIN_DATETIME",
  "D_JZSJ"	"DOMAIN_DATETIME",
  "D_CZYXM"	"DOMAIN_XM",
  "D_BZ"	"DOMAIN_BZ",
  "D_YSRQ"	"DOMAIN_C8",
CONSTRAINT "KRJZ1D_KRJZ" PRIMARY KEY ("D_JZBH", "D_HH")
);

/* Table: KRLY, Owner: SYSDBA */

CREATE TABLE "KRLY" 
(
  "D_LYRQ"	"DOMAIN_DATETIME",
  "D_LYSJ"	"DOMAIN_DATETIME",
  "D_LYLX"	"DOMAIN_ZT",
  "D_KFBH"	"DOMAIN_BH",
  "D_KRXM"	"DOMAIN_XM",
  "D_LYDX"	"DOMAIN_XM",
  "D_NR"	"DOMAIN_MEMO"
);

/* Table: KRXX, Owner: SYSDBA */

CREATE TABLE "KRXX" 
(
  "D_KRBH"	"DOMAIN_USEBH" NOT NULL,
  "D_KRXM"	"DOMAIN_LXM",
  "D_KRLX"	"DOMAIN_ZT",
  "D_DDRQ"	"DOMAIN_DATETIME",
  "D_DDSJ"	"DOMAIN_DATETIME",
  "D_LDRQ"	"DOMAIN_DATETIME",
  "D_LDSJ"	"DOMAIN_DATETIME",
  "D_YWX"	"DOMAIN_XM",
  "D_YWM"	"DOMAIN_XM",
  "D_XB"	"DOMAIN_C2",
  "D_MZBH"	"DOMAIN_BH",
  "D_DQBH"	"DOMAIN_BH",
  "D_GBBH"	"DOMAIN_BH",
  "D_NZTS"	"DOMAIN_SL",
  "D_TLSY"	"DOMAIN_C10",
  "D_ZJBH"	"DOMAIN_BH",
  "D_ZJHM"	"DOMAIN_C18",
  "D_CSNY"	"DOMAIN_DATETIME",
  "D_HCL"	"DOMAIN_C10",
  "D_HCQ"	"DOMAIN_C10",
  "D_QZBH"	"DOMAIN_BH",
  "D_QZYXQ"	"DOMAIN_DATETIME",
  "D_ZY"	"DOMAIN_C10",
  "D_LXDH"	"DOMAIN_C16",
  "D_DWMC"	"DOMAIN_BZ",
  "D_JTDZ"	"DOMAIN_BZ",
  "D_JDR"	"DOMAIN_XM",
  "D_JDDW"	"DOMAIN_BZ",
  "D_BZ"	"DOMAIN_BZ",
  "D_QDR1"	"DOMAIN_XM",
  "D_QDR2"	"DOMAIN_XM",
  "D_QDR3"	"DOMAIN_XM",
  "D_QDR4"	"DOMAIN_XM",
CONSTRAINT "D_KRXX" PRIMARY KEY ("D_KRBH")
);

/* Table: KRXXDA, Owner: SYSDBA */

CREATE TABLE "KRXXDA" 
(
  "D_KRBH"	"DOMAIN_USEBH" NOT NULL,
  "D_KRXM"	"DOMAIN_LXM",
  "D_KRLX"	"DOMAIN_ZT",
  "D_DDRQ"	"DOMAIN_DATETIME",
  "D_DDSJ"	"DOMAIN_DATETIME",
  "D_LDRQ"	"DOMAIN_DATETIME",
  "D_LDSJ"	"DOMAIN_DATETIME",
  "D_YWX"	"DOMAIN_XM",
  "D_YWM"	"DOMAIN_XM",
  "D_XB"	"DOMAIN_C2",
  "D_MZBH"	"DOMAIN_BH",
  "D_DQBH"	"DOMAIN_BH",
  "D_GBBH"	"DOMAIN_BH",
  "D_NZTS"	"DOMAIN_SL",
  "D_TLSY"	"DOMAIN_C10",
  "D_ZJBH"	"DOMAIN_BH",
  "D_ZJHM"	"DOMAIN_C18",
  "D_CSNY"	"DOMAIN_DATETIME",
  "D_HCL"	"DOMAIN_C10",
  "D_HCQ"	"DOMAIN_C10",
  "D_QZBH"	"DOMAIN_BH",
  "D_QZYXQ"	"DOMAIN_DATETIME",
  "D_ZY"	"DOMAIN_C10",
  "D_LXDH"	"DOMAIN_C16",
  "D_DWMC"	"DOMAIN_BZ",
  "D_JTDZ"	"DOMAIN_BZ",
  "D_JDR"	"DOMAIN_XM",
  "D_JDDW"	"DOMAIN_BZ",
  "D_BZ"	"DOMAIN_BZ",
  "D_QDR1"	"DOMAIN_XM",
  "D_QDR2"	"DOMAIN_XM",
  "D_QDR3"	"DOMAIN_XM",
  "D_QDR4"	"DOMAIN_XM",
CONSTRAINT "KRXX1D_KRXX" PRIMARY KEY ("D_KRBH")
);

/* Table: KRYJ, Owner: SYSDBA */

CREATE TABLE "KRYJ" 
(
  "D_YJBH"	"DOMAIN_USEBH" NOT NULL,
  "D_HH"	"DOMAIN_SL" NOT NULL,
  "D_FKFS"	"DOMAIN_FS",
  "D_XYKBH"	"DOMAIN_BH",
  "D_KHBH"	"DOMAIN_BH",
  "D_YFJE"	"DOMAIN_CURRENCY",
  "D_YFRQ"	"DOMAIN_DATETIME",
  "D_YFSJ"	"DOMAIN_DATETIME",
  "D_BZ"	"DOMAIN_BZ",
CONSTRAINT "D_KRYJ" PRIMARY KEY ("D_YJBH", "D_HH")
);

/* Table: KRZD, Owner: SYSDBA */

CREATE TABLE "KRZD" 
(
  "D_ZDBH"	"DOMAIN_USEBH" NOT NULL,
  "D_HH"	"DOMAIN_SL" NOT NULL,
  "D_ZDLB"	"DOMAIN_ZT",
  "D_KRBH"	"DOMAIN_USEBH",
  "D_YJBH"	"DOMAIN_USEBH",
  "D_KFBH"	"DOMAIN_BH",
  "D_SJFJ"	"DOMAIN_CURRENCY",
  "D_XMBH"	"DOMAIN_BH",
  "D_XFDJ"	"DOMAIN_CURRENCY",
  "D_XFSL"	"DOMAIN_SLF",
  "D_XFJE"	"DOMAIN_CURRENCY",
  "D_XFRQ"	"DOMAIN_DATETIME",
  "D_XFSJ"	"DOMAIN_DATETIME",
  "D_YHJE"	"DOMAIN_CURRENCY",
  "D_JZRQ"	"DOMAIN_DATETIME",
  "D_JZSJ"	"DOMAIN_DATETIME",
  "D_JZBZ"	"DOMAIN_ZT",
  "D_JSBZ"	"DOMAIN_ZT",
  "D_DLR1"	"DOMAIN_XM",
  "D_DLR2"	"DOMAIN_XM",
  "D_DLR3"	"DOMAIN_XM",
  "D_DLR4"	"DOMAIN_XM",
  "D_CZYXM"	"DOMAIN_XM",
  "D_JZYXM"	"DOMAIN_XM",
  "D_TYR"	"DOMAIN_XM",
  "D_BZ"	"DOMAIN_BZ",
  "D_YSRQ"	"DOMAIN_C8",
  "D_JZBH"	"DOMAIN_USEBH",
CONSTRAINT "D_KRZD" PRIMARY KEY ("D_ZDBH", "D_HH")
);

/* Table: KRZDDA, Owner: SYSDBA */

CREATE TABLE "KRZDDA" 
(
  "D_ZDBH"	"DOMAIN_USEBH" NOT NULL,
  "D_HH"	"DOMAIN_SL" NOT NULL,
  "D_ZDLB"	"DOMAIN_ZT",
  "D_KRBH"	"DOMAIN_USEBH",
  "D_YJBH"	"DOMAIN_USEBH",
  "D_KFBH"	"DOMAIN_BH",
  "D_SJFJ"	"DOMAIN_CURRENCY",
  "D_XMBH"	"DOMAIN_BH",
  "D_XFDJ"	"DOMAIN_CURRENCY",
  "D_XFSL"	"DOMAIN_SLF",
  "D_XFJE"	"DOMAIN_CURRENCY",
  "D_XFRQ"	"DOMAIN_DATETIME",
  "D_XFSJ"	"DOMAIN_DATETIME",
  "D_YHJE"	"DOMAIN_CURRENCY",
  "D_JZRQ"	"DOMAIN_DATETIME",
  "D_JZSJ"	"DOMAIN_DATETIME",
  "D_JZBZ"	"DOMAIN_ZT",
  "D_JSBZ"	"DOMAIN_ZT",
  "D_DLR1"	"DOMAIN_XM",
  "D_DLR2"	"DOMAIN_XM",
  "D_DLR3"	"DOMAIN_XM",
  "D_DLR4"	"DOMAIN_XM",
  "D_CZYXM"	"DOMAIN_XM",
  "D_JZYXM"	"DOMAIN_XM",
  "D_TYR"	"DOMAIN_XM",
  "D_BZ"	"DOMAIN_BZ",
  "D_YSRQ"	"DOMAIN_C8",
  "D_JZBH"	"DOMAIN_USEBH",
CONSTRAINT "KRZD1D_KRZD" PRIMARY KEY ("D_ZDBH", "D_HH")
);

/* Table: LCDM, Owner: SYSDBA */

CREATE TABLE "LCDM" 
(
  "D_LCBH"	"DOMAIN_BH" NOT NULL,
  "D_LCMC"	"DOMAIN_MC" NOT NULL,
  "D_DM"	"DOMAIN_DM",
CONSTRAINT "D_LCDM" PRIMARY KEY ("D_LCBH")
);

/* Table: LCSK, Owner: SYSDBA */

CREATE TABLE "LCSK" 
(
  "D_LCCC"	"DOMAIN_BH",
  "D_HH"	"DOMAIN_SL",
  "D_LCLX"	"DOMAIN_C20",
  "D_SFZ"	"DOMAIN_DM",
  "D_ZDZ"	"DOMAIN_DM",
  "D_SFSJ"	"DOMAIN_DATETIME",
  "D_ZDSJ"	"DOMAIN_DATETIME",
  "D_ZJZ"	"DOMAIN_DM",
  "D_DZSJ"	"DOMAIN_DATETIME"
);

/* Table: LCTJ, Owner: SYSDBA */

CREATE TABLE "LCTJ" 
(
  "D_YSRQ"	"DOMAIN_C8" NOT NULL,
  "D_LCBH"	"DOMAIN_BH" NOT NULL,
  "D_FJS"	"DOMAIN_SL",
  "D_CZS"	"DOMAIN_SL",
  "D_QJS"	"DOMAIN_SL",
  "D_BJS"	"DOMAIN_SL",
  "D_JJFJ"	"DOMAIN_CURRENCY",
  "D_RCZL"	"DOMAIN_SLF",
  "D_YCZL"	"DOMAIN_SLF",
CONSTRAINT "D_LCTJ" PRIMARY KEY ("D_YSRQ", "D_LCBH")
);

/* Table: LCTJDA, Owner: SYSDBA */

CREATE TABLE "LCTJDA" 
(
  "D_YSRQ"	"DOMAIN_C8" NOT NULL,
  "D_LCBH"	"DOMAIN_BH" NOT NULL,
  "D_FJS"	"DOMAIN_SL",
  "D_CZS"	"DOMAIN_SL",
  "D_QJS"	"DOMAIN_SL",
  "D_BJS"	"DOMAIN_SL",
  "D_JJFJ"	"DOMAIN_CURRENCY",
  "D_RCZL"	"DOMAIN_SLF",
  "D_YCZL"	"DOMAIN_SLF",
CONSTRAINT "LCTJ1D_LCTJ" PRIMARY KEY ("D_YSRQ", "D_LCBH")
);

/* Table: LKYSKZ, Owner: SYSDBA */

CREATE TABLE "LKYSKZ" 
(
  "D_YSRQ"	"DOMAIN_C8" NOT NULL,
  "D_XMBH"	"DOMAIN_BH" NOT NULL,
  "D_XFJE"	"DOMAIN_CURRENCY",
  "D_YJJE"	"DOMAIN_CURRENCY",
CONSTRAINT "D_LKYSKZ" PRIMARY KEY ("D_YSRQ", "D_XMBH")
);

/* Table: LKYSKZDA, Owner: SYSDBA */

CREATE TABLE "LKYSKZDA" 
(
  "D_YSRQ"	"DOMAIN_C8" NOT NULL,
  "D_XMBH"	"DOMAIN_BH" NOT NULL,
  "D_XFJE"	"DOMAIN_CURRENCY",
  "D_YJJE"	"DOMAIN_CURRENCY",
CONSTRAINT "LKYSKZ1D_LKYSKZ" PRIMARY KEY ("D_YSRQ", "D_XMBH")
);

/* Table: MZDM, Owner: SYSDBA */

CREATE TABLE "MZDM" 
(
  "D_MZBH"	"DOMAIN_BH" NOT NULL,
  "D_MZMC"	"DOMAIN_MC" NOT NULL,
  "D_DM"	"DOMAIN_DM",
CONSTRAINT "D_MZDM" PRIMARY KEY ("D_MZBH")
);

/* Table: NEWDATA, Owner: SYSDBA */

CREATE TABLE "NEWDATA" 
(
  "CLASS"	"DOMAIN_BH",
  "ROOM"	"DOMAIN_BH",
  "PLACE"	"DOMAIN_C12",
  "NUMBER"	"DOMAIN_C16",
  "SDATE"	"DOMAIN_C8",
  "STIME"	"DOMAIN_C6",
  "LAST"	"DOMAIN_SLF",
  "UNIT"	"DOMAIN_CURRENCY",
  "FEE"	"DOMAIN_CURRENCY",
  "ADDI_FEE"	"DOMAIN_CURRENCY",
  "SVC_FEE"	"DOMAIN_CURRENCY",
  "TOTAL"	"DOMAIN_CURRENCY",
  "FLTY"	"DOMAIN_SL"
);

/* Table: OLDDATA, Owner: SYSDBA */

CREATE TABLE "OLDDATA" 
(
  "CLASS"	"DOMAIN_BH",
  "ROOM"	"DOMAIN_BH",
  "PLACE"	"DOMAIN_C12",
  "NUMBER"	"DOMAIN_C16",
  "SDATE"	"DOMAIN_C8",
  "STIME"	"DOMAIN_C6",
  "LAST"	"DOMAIN_SLF",
  "UNIT"	"DOMAIN_CURRENCY",
  "FEE"	"DOMAIN_CURRENCY",
  "ADDI_FEE"	"DOMAIN_CURRENCY",
  "SVC_FEE"	"DOMAIN_CURRENCY",
  "TOTAL"	"DOMAIN_CURRENCY",
  "FLTY"	"DOMAIN_SL"
);

/* Table: QZDM, Owner: SYSDBA */

CREATE TABLE "QZDM" 
(
  "D_QZBH"	"DOMAIN_BH" NOT NULL,
  "D_QZMC"	"DOMAIN_MC" NOT NULL,
  "D_DM"	"DOMAIN_DM",
CONSTRAINT "D_QZDM" PRIMARY KEY ("D_QZBH")
);

/* Table: SHFARE, Owner: SYSDBA */

CREATE TABLE "SHFARE" 
(
  "PLACE"	"DOMAIN_C20",
  "CODE"	"DOMAIN_C6",
  "UNIT"	"DOMAIN_CURRENCY",
  "PRICE"	"DOMAIN_SLF",
  "JFYN"	"DOMAIN_LOGIC",
  "NHYN"	"DOMAIN_LOGIC"
);

/* Table: SIGCODE, Owner: SYSDBA */

CREATE TABLE "SIGCODE" 
(
  "CLASS"	"DOMAIN_C4",
  "CLASSNAME"	"DOMAIN_C10",
  "ROOM"	"DOMAIN_BH",
  "JFYN"	"DOMAIN_LOGIC",
  "TOTAL"	"DOMAIN_CURRENCY"
);

/* Table: SJTJ, Owner: SYSDBA */

CREATE TABLE "SJTJ" 
(
  "D_YSRQ"	"DOMAIN_C8" NOT NULL,
  "D_FPE"	"DOMAIN_CURRENCY",
  "D_LKYSK"	"DOMAIN_CURRENCY",
  "D_KHYSK"	"DOMAIN_CURRENCY",
  "D_CWSJE"	"DOMAIN_CURRENCY",
  "D_CTFPE"	"DOMAIN_CURRENCY",
  "D_CTSHE"	"DOMAIN_CURRENCY",
  "D_CTSJE"	"DOMAIN_CURRENCY",
CONSTRAINT "D_SJTJ" PRIMARY KEY ("D_YSRQ")
);

/* Table: XMDM, Owner: SYSDBA */

CREATE TABLE "XMDM" 
(
  "D_XMBH"	"DOMAIN_BH" NOT NULL,
  "D_XMMC"	"DOMAIN_MC" NOT NULL,
  "D_XFBZ"	"DOMAIN_LOGIC",
  "D_DM"	"DOMAIN_DM",
CONSTRAINT "D_XMDM" PRIMARY KEY ("D_XMBH")
);

/* Table: XXDC, Owner: SYSDBA */

CREATE TABLE "XXDC" 
(
  "D_KRBH"	"DOMAIN_USEBH" NOT NULL,
  "D_KFBH"	"DOMAIN_BH",
  "D_DDRQ"	"DOMAIN_C8",
  "D_LDRQ"	"DOMAIN_C8",
  "D_KRXM"	"DOMAIN_XM",
  "D_XB"	"DOMAIN_C2",
  "D_CSNY"	"DOMAIN_C8",
  "D_MZ"	"DOMAIN_C10",
  "D_JG"	"DOMAIN_C10",
  "D_GZDW"	"DOMAIN_BZ",
  "D_ZY"	"DOMAIN_C10",
  "D_JTDZ"	"DOMAIN_BZ",
  "D_ZJLX"	"DOMAIN_C10",
  "D_ZJHM"	"DOMAIN_C18",
CONSTRAINT "D_XXDC" PRIMARY KEY ("D_KRBH")
);

/* Table: XYK, Owner: SYSDBA */

CREATE TABLE "XYK" 
(
  "D_XYKBH"	"DOMAIN_BH" NOT NULL,
  "D_XYKMC"	"DOMAIN_MC" NOT NULL,
  "D_DM"	"DOMAIN_DM",
CONSTRAINT "D_XYK" PRIMARY KEY ("D_XYKBH")
);

/* Table: YDCY, Owner: SYSDBA */

CREATE TABLE "YDCY" 
(
  "D_YDBH"	"DOMAIN_USEBH" NOT NULL,
  "D_CTBH"	"DOMAIN_BH" NOT NULL,
  "D_CTMC"	"DOMAIN_MC",
  "D_KRBH"	"DOMAIN_USEBH",
  "D_KRXM"	"DOMAIN_LXM",
  "D_YDRQ"	"DOMAIN_DATETIME",
  "D_SYRQ"	"DOMAIN_DATETIME",
  "D_SYSJ"	"DOMAIN_DATETIME",
  "D_SJDM"	"DOMAIN_SJ",
  "D_YCBZ"	"DOMAIN_BZ",
  "D_YCLX"	"DOMAIN_SL",
  "D_RS"	"DOMAIN_SL",
  "D_DJ"	"DOMAIN_CURRENCY",
  "D_XFSL"	"DOMAIN_SLF",
  "D_XFJE"	"DOMAIN_CURRENCY",
  "D_YDBZ"	"DOMAIN_ZT",
  "D_RZBZ"	"DOMAIN_LOGIC",
  "D_KTBZ"	"DOMAIN_LOGIC",
  "D_JSBZ"	"DOMAIN_ZT",
  "D_BZ"	"DOMAIN_MEMO",
  "D_CZYXM"	"DOMAIN_XM",
CONSTRAINT "D_YDCY" PRIMARY KEY ("D_YDBH", "D_CTBH")
);

/* Table: YDHC, Owner: SYSDBA */

CREATE TABLE "YDHC" 
(
  "D_YDBH"	"DOMAIN_USEBH" NOT NULL,
  "D_KRBH"	"DOMAIN_USEBH",
  "D_KRXM"	"DOMAIN_LXM",
  "D_YDRQ"	"DOMAIN_DATETIME",
  "D_SYRQ"	"DOMAIN_DATETIME",
  "D_SYSJ"	"DOMAIN_DATETIME",
  "D_SJDM"	"DOMAIN_SJ",
  "D_HCBH"	"DOMAIN_BH",
  "D_HCMC"	"DOMAIN_MC",
  "D_HCZJ"	"DOMAIN_CURRENCY",
  "D_HCRS"	"DOMAIN_SL",
  "D_HCRS1"	"DOMAIN_SL",
  "D_HFSL"	"DOMAIN_SLF",
  "D_HFJE"	"DOMAIN_CURRENCY",
  "D_HFBZ"	"DOMAIN_BZ",
  "D_XHSL"	"DOMAIN_SLF",
  "D_XHJE"	"DOMAIN_CURRENCY",
  "D_XHBZ"	"DOMAIN_BZ",
  "D_SGSL"	"DOMAIN_SLF",
  "D_SGJE"	"DOMAIN_CURRENCY",
  "D_SGBZ"	"DOMAIN_BZ",
  "D_QTJE"	"DOMAIN_CURRENCY",
  "D_QTBZ"	"DOMAIN_BZ",
  "D_HTSL"	"DOMAIN_SLF",
  "D_HTBZ"	"DOMAIN_BZ",
  "D_BZ"	"DOMAIN_BZ",
  "D_RZBZ"	"DOMAIN_LOGIC",
  "D_JSBZ"	"DOMAIN_ZT",
  "D_CZYXM"	"DOMAIN_XM",
CONSTRAINT "D_YDHC" PRIMARY KEY ("D_YDBH")
);

/* Table: YDKF, Owner: SYSDBA */

CREATE TABLE "YDKF" 
(
  "D_YDBH"	"DOMAIN_USEBH" NOT NULL,
  "D_KFBH"	"DOMAIN_BH" NOT NULL,
  "D_KRBH"	"DOMAIN_USEBH",
  "D_KRXM"	"DOMAIN_LXM",
  "D_YDRQ"	"DOMAIN_DATETIME",
  "D_DDRQ"	"DOMAIN_DATETIME",
  "D_DDSJ"	"DOMAIN_DATETIME",
  "D_LDRQ"	"DOMAIN_DATETIME",
  "D_LDSJ"	"DOMAIN_DATETIME",
  "D_XFJE"	"DOMAIN_CURRENCY",
  "D_YDBZ"	"DOMAIN_ZT",
  "D_RZBZ"	"DOMAIN_LOGIC",
  "D_JSBZ"	"DOMAIN_ZT",
  "D_CZYXM"	"DOMAIN_XM",
  "D_BZ"	"DOMAIN_BZ",
CONSTRAINT "D_YDKF" PRIMARY KEY ("D_YDBH", "D_KFBH")
);

/* Table: YDXX, Owner: SYSDBA */

CREATE TABLE "YDXX" 
(
  "D_KRBH"	"DOMAIN_USEBH" NOT NULL,
  "D_KRXM"	"DOMAIN_LXM",
  "D_FKFS"	"DOMAIN_FS",
  "D_XYKBH"	"DOMAIN_BH",
  "D_KHBH"	"DOMAIN_BH",
  "D_YFJE"	"DOMAIN_CURRENCY",
  "D_DWMC"	"DOMAIN_BZ",
  "D_LXDH"	"DOMAIN_C16",
  "D_LXR"	"DOMAIN_XM",
  "D_BZ"	"DOMAIN_BZ",
  "D_CZYXM"	"DOMAIN_XM",
CONSTRAINT "D_YDXX" PRIMARY KEY ("D_KRBH")
);

/* Table: YGDA, Owner: SYSDBA */

CREATE TABLE "YGDA" 
(
  "D_YGBH"	"DOMAIN_BH" NOT NULL,
  "D_YGXM"	"DOMAIN_XM" NOT NULL,
  "D_BMBH"	"DOMAIN_BH" NOT NULL,
  "D_KL"	"DOMAIN_C8",
  "D_DM"	"DOMAIN_DM",
CONSTRAINT "D_YGBH" PRIMARY KEY ("D_YGBH")
);

/* Table: YGKF, Owner: SYSDBA */

CREATE TABLE "YGKF" 
(
  "D_CZYXM"	"DOMAIN_XM",
  "D_KFRQ"	"DOMAIN_DATETIME",
  "D_KFSJ"	"DOMAIN_DATETIME",
  "D_KFBH"	"DOMAIN_BH",
  "D_KRXM"	"DOMAIN_LXM",
  "D_SJFJ"	"DOMAIN_CURRENCY"
);

/* Table: YGQX, Owner: SYSDBA */

CREATE TABLE "YGQX" 
(
  "D_YGBH"	"DOMAIN_BH" NOT NULL,
  "D_CZBH"	"DOMAIN_BH" NOT NULL,
  "D_CZXM"	"DOMAIN_C20",
  "D_QX"	"DOMAIN_LOGIC",
CONSTRAINT "D_YGQX" PRIMARY KEY ("D_YGBH", "D_CZBH")
);

/* Table: YSK, Owner: SYSDBA */

CREATE TABLE "YSK" 
(
  "D_KHBH"	"DOMAIN_BH" NOT NULL,
  "D_ZDBH"	"DOMAIN_USEBH" NOT NULL,
  "D_HH"	"DOMAIN_SL" NOT NULL,
  "D_XMBH"	"DOMAIN_BH",
  "D_XFDJ"	"DOMAIN_CURRENCY",
  "D_XFSL"	"DOMAIN_SLF",
  "D_XFJE"	"DOMAIN_CURRENCY",
  "D_XFRQ"	"DOMAIN_DATETIME",
  "D_XFSJ"	"DOMAIN_DATETIME",
  "D_CZYXM"	"DOMAIN_XM",
  "D_BZ"	"DOMAIN_BZ",
CONSTRAINT "D_YSK" PRIMARY KEY ("D_KHBH", "D_ZDBH", "D_HH")
);

/* Table: YSKJZ, Owner: SYSDBA */

CREATE TABLE "YSKJZ" 
(
  "D_JZBH"	"DOMAIN_USEBH" NOT NULL,
  "D_KHBH"	"DOMAIN_BH" NOT NULL,
  "D_HH"	"DOMAIN_SL" NOT NULL,
  "D_XMBH"	"DOMAIN_BH",
  "D_XFJE"	"DOMAIN_CURRENCY",
  "D_YJJE"	"DOMAIN_CURRENCY",
  "D_YHJE"	"DOMAIN_CURRENCY",
  "D_JZJE"	"DOMAIN_CURRENCY",
  "D_JZFS"	"DOMAIN_FS",
  "D_XYKBH"	"DOMAIN_BH",
  "D_JZRQ"	"DOMAIN_DATETIME",
  "D_JZSJ"	"DOMAIN_DATETIME",
  "D_CZYXM"	"DOMAIN_XM",
  "D_BZ"	"DOMAIN_BZ",
CONSTRAINT "D_YSKJZ" PRIMARY KEY ("D_JZBH", "D_KHBH", "D_HH")
);

/* Table: YSKJZLS, Owner: SYSDBA */

CREATE TABLE "YSKJZLS" 
(
  "D_KHBH"	"DOMAIN_BH" NOT NULL,
  "D_ZDBH"	"DOMAIN_USEBH" NOT NULL,
  "D_HH"	"DOMAIN_SL" NOT NULL,
  "D_XMBH"	"DOMAIN_BH",
  "D_XFJE"	"DOMAIN_CURRENCY",
  "D_YJJE"	"DOMAIN_CURRENCY",
  "D_YHJE"	"DOMAIN_CURRENCY",
  "D_JZJE"	"DOMAIN_CURRENCY",
  "D_XFRQ"	"DOMAIN_DATETIME",
  "D_XFSJ"	"DOMAIN_DATETIME",
  "D_JZBZ"	"DOMAIN_LOGIC",
CONSTRAINT "D_YSKJZLS" PRIMARY KEY ("D_KHBH", "D_ZDBH", "D_HH")
);

/* Table: YYTJ, Owner: SYSDBA */

CREATE TABLE "YYTJ" 
(
  "D_YSRQ"	"DOMAIN_C8" NOT NULL,
  "D_XMBH"	"DOMAIN_BH" NOT NULL,
  "D_JRYY"	"DOMAIN_CURRENCY",
  "D_JRSH"	"DOMAIN_CURRENCY",
  "D_JRYH"	"DOMAIN_CURRENCY",
  "D_BYYY"	"DOMAIN_CURRENCY",
  "D_BYYH"	"DOMAIN_CURRENCY",
  "D_LJYY"	"DOMAIN_CURRENCY",
  "D_LJYH"	"DOMAIN_CURRENCY",
  "D_LJSH"	"DOMAIN_CURRENCY",
  "D_LJYS"	"DOMAIN_CURRENCY",
  "D_ZRBYYY"	"DOMAIN_CURRENCY",
  "D_ZRBYYH"	"DOMAIN_CURRENCY",
  "D_ZRLJYY"	"DOMAIN_CURRENCY",
  "D_ZRLJYH"	"DOMAIN_CURRENCY",
  "D_ZRLJSH"	"DOMAIN_CURRENCY",
  "D_ZRLJYS"	"DOMAIN_CURRENCY",
CONSTRAINT "D_YYTJ" PRIMARY KEY ("D_YSRQ", "D_XMBH")
);

/* Table: YYTJDA, Owner: SYSDBA */

CREATE TABLE "YYTJDA" 
(
  "D_YSRQ"	"DOMAIN_C8" NOT NULL,
  "D_XMBH"	"DOMAIN_BH" NOT NULL,
  "D_JRYY"	"DOMAIN_CURRENCY",
  "D_JRSH"	"DOMAIN_CURRENCY",
  "D_JRYH"	"DOMAIN_CURRENCY",
  "D_BYYY"	"DOMAIN_CURRENCY",
  "D_BYYH"	"DOMAIN_CURRENCY",
  "D_LJYY"	"DOMAIN_CURRENCY",
  "D_LJYH"	"DOMAIN_CURRENCY",
  "D_LJSH"	"DOMAIN_CURRENCY",
  "D_LJYS"	"DOMAIN_CURRENCY",
  "D_ZRBYYY"	"DOMAIN_CURRENCY",
  "D_ZRBYYH"	"DOMAIN_CURRENCY",
  "D_ZRLJYY"	"DOMAIN_CURRENCY",
  "D_ZRLJYH"	"DOMAIN_CURRENCY",
  "D_ZRLJSH"	"DOMAIN_CURRENCY",
  "D_ZRLJYS"	"DOMAIN_CURRENCY",
CONSTRAINT "YYTJ1D_YYTJ" PRIMARY KEY ("D_YSRQ", "D_XMBH")
);

/* Table: ZJDM, Owner: SYSDBA */

CREATE TABLE "ZJDM" 
(
  "D_ZJBH"	"DOMAIN_BH" NOT NULL,
  "D_ZJMC"	"DOMAIN_MC" NOT NULL,
  "D_DM"	"DOMAIN_DM",
CONSTRAINT "D_ZJDM" PRIMARY KEY ("D_ZJBH")
);


/* Grant Roles for this database */


/* Grant permissions for this database */

