unit DmBb;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics, Controls, Forms, Dialogs,
  Db, DBClient, MConnect;

type
  TDataBb = class(TDataModule)
    KhXsHz: TClientDataSet;
    KhXsHzID: TIntegerField;
    KhXsHzBH: TWideStringField;
    KhXsHzMC: TWideStringField;
    KhXsHzJE: TFloatField;
    KhXsHzJE2: TFloatField;
    KhXsHzJE3: TFloatField;
    KhXsMx: TClientDataSet;
    KhXsMxDJBH: TWideStringField;
    KhXsMxRQ: TDateField;
    KhXsMxBH: TWideStringField;
    KhXsMxPM: TWideStringField;
    KhXsMxDW: TWideStringField;
    KhXsMxJEA: TFloatField;
    KhXsMxJEB: TFloatField;
    KhXsMxJEC: TFloatField;
    KhXsMxSL: TFloatField;
    KhXsMxDJ: TFloatField;
    KhXsMxNSL: TFloatField;
    KhXsMxZBID: TIntegerField;
    KhXsHzcMC: TStringField;
    HpXsHz: TClientDataSet;
    IntegerField3: TIntegerField;
    FloatField1: TFloatField;
    FloatField2: TFloatField;
    FloatField3: TFloatField;
    StringField1: TStringField;
    HpXsMx: TClientDataSet;
    IntegerField4: TIntegerField;
    DateField1: TDateField;
    WideStringField3: TWideStringField;
    FloatField4: TFloatField;
    FloatField5: TFloatField;
    FloatField6: TFloatField;
    FloatField7: TFloatField;
    FloatField8: TFloatField;
    FloatField9: TFloatField;
    HpXsHzBH: TWideStringField;
    HpXsHzPM: TWideStringField;
    HpXsHzDW: TWideStringField;
    HpXsHzSL: TFloatField;
    HpXsMxBH: TWideStringField;
    HpXsMxMC: TWideStringField;
    YwyXsHz: TClientDataSet;
    FloatField11: TFloatField;
    FloatField12: TFloatField;
    FloatField13: TFloatField;
    StringField2: TStringField;
    YwyXsMx: TClientDataSet;
    IntegerField6: TIntegerField;
    DateField2: TDateField;
    WideStringField5: TWideStringField;
    WideStringField6: TWideStringField;
    WideStringField7: TWideStringField;
    FloatField17: TFloatField;
    FloatField18: TFloatField;
    FloatField19: TFloatField;
    YwyXsHzYWY: TWideStringField;
    DqXsHz: TClientDataSet;
    WideStringField1: TWideStringField;
    FloatField10: TFloatField;
    FloatField14: TFloatField;
    FloatField15: TFloatField;
    StringField3: TStringField;
    DqXsMx: TClientDataSet;
    IntegerField5: TIntegerField;
    DateField3: TDateField;
    WideStringField2: TWideStringField;
    WideStringField4: TWideStringField;
    WideStringField8: TWideStringField;
    FloatField16: TFloatField;
    FloatField20: TFloatField;
    FloatField21: TFloatField;
    sKhXsHz: TDataSource;
    sKhXsMx: TDataSource;
    sHpXsHz: TDataSource;
    sHpXsMx: TDataSource;
    sYwyXsHz: TDataSource;
    sYwyXsMx: TDataSource;
    sDqXsHz: TDataSource;
    sDqXsMx: TDataSource;
    HplbXsHz: TClientDataSet;
    WideStringField9: TWideStringField;
    FloatField22: TFloatField;
    FloatField23: TFloatField;
    FloatField24: TFloatField;
    StringField4: TStringField;
    HplbXsMx: TClientDataSet;
    IntegerField7: TIntegerField;
    DateField4: TDateField;
    WideStringField10: TWideStringField;
    WideStringField11: TWideStringField;
    WideStringField12: TWideStringField;
    FloatField25: TFloatField;
    FloatField26: TFloatField;
    FloatField27: TFloatField;
    sHplbXsHz: TDataSource;
    sHplbXsMx: TDataSource;
    HplbXsMxBH: TWideStringField;
    HplbXsMxPM: TWideStringField;
    HplbXsMxDW: TWideStringField;
    HplbXsMxSL: TFloatField;
    HplbXsMxDJ: TFloatField;
    HplbXsMxNSL: TFloatField;
    HpXsMlHz: TClientDataSet;
    IntegerField8: TIntegerField;
    WideStringField13: TWideStringField;
    WideStringField14: TWideStringField;
    WideStringField15: TWideStringField;
    FloatField29: TFloatField;
    StringField5: TStringField;
    HpXsMlMx: TClientDataSet;
    IntegerField9: TIntegerField;
    DateField5: TDateField;
    WideStringField16: TWideStringField;
    WideStringField17: TWideStringField;
    WideStringField18: TWideStringField;
    FloatField32: TFloatField;
    FloatField33: TFloatField;
    FloatField35: TFloatField;
    sHpXsMlHz: TDataSource;
    sHpXsMlMx: TDataSource;
    HpXsMlMxCBDJ: TFloatField;
    HpXsMlHzCBJE: TFloatField;
    HpXsMlHzLRJE: TFloatField;
    HpXsMlMxCBJE: TFloatField;
    HpXsMlMxLRJE: TFloatField;
    XsMlAdjs: TClientDataSet;
    IntegerField10: TIntegerField;
    DateField6: TDateField;
    WideStringField19: TWideStringField;
    FloatField34: TFloatField;
    FloatField36: TFloatField;
    FloatField37: TFloatField;
    sXsMlAdjs: TDataSource;
    XsMlAdjsBH: TWideStringField;
    XsMlAdjsMC: TWideStringField;
    KhXsMxLX: TWideStringField;
    HpXsMxLX: TWideStringField;
    YwyXsMxWideStringField: TWideStringField;
    DqXsMxLX: TWideStringField;
    HplbXsMxLX: TWideStringField;
    HpXsMlMxLX: TWideStringField;
    XsMlAdjsLX: TWideStringField;
    YwyYjtj: TClientDataSet;
    XsddQk: TClientDataSet;
    IntegerField12: TIntegerField;
    DateField7: TDateField;
    WideStringField24: TWideStringField;
    WideStringField25: TWideStringField;
    WideStringField26: TWideStringField;
    FloatField42: TFloatField;
    XsMsdj: TClientDataSet;
    XsMlNb: TClientDataSet;
    IntegerField13: TIntegerField;
    sYwyYjtj: TDataSource;
    sXsddQk: TDataSource;
    sXsMsdj: TDataSource;
    sXsMlNb: TDataSource;
    YwyYjtjYWY: TWideStringField;
    YwyYjtjJEA: TFloatField;
    YwyYjtjJEB: TFloatField;
    YwyYjtjJEC: TFloatField;
    YwyYjtjJEA2: TFloatField;
    XsddQkBH: TWideStringField;
    XsMsdjID: TIntegerField;
    XsMsdjRQ: TDateField;
    XsMsdjDJBH: TWideStringField;
    XsMsdjBH: TWideStringField;
    XsMsdjMC: TWideStringField;
    XsMsdjJE: TFloatField;
    XsMsdjJE2: TFloatField;
    XsMsdjJE3: TFloatField;
    XsMlNbMx: TClientDataSet;
    sXsMlNbMx: TDataSource;
    XsMlNbJEA: TFloatField;
    XsMlNbCBJE: TFloatField;
    XsMlNbLRJE: TFloatField;
    XsMlNbMxLX: TWideStringField;
    XsMlNbMxZBID: TIntegerField;
    XsMlNbMxRQ: TDateField;
    XsMlNbMxDJBH: TWideStringField;
    XsMlNbMxBH: TWideStringField;
    XsMlNbMxPM: TWideStringField;
    XsMlNbMxDW: TWideStringField;
    XsMlNbMxSL: TFloatField;
    XsMlNbMxDJ: TFloatField;
    XsMlNbMxCBDJ: TFloatField;
    XsMlNbMxJEA: TFloatField;
    XsMlNbMxCBJE: TFloatField;
    XsMlNbMxLRJE: TFloatField;
    GysGhHz: TClientDataSet;
    IntegerField11: TIntegerField;
    WideStringField20: TWideStringField;
    WideStringField21: TWideStringField;
    FloatField28: TFloatField;
    FloatField30: TFloatField;
    FloatField31: TFloatField;
    StringField6: TStringField;
    GysGhMx: TClientDataSet;
    WideStringField22: TWideStringField;
    IntegerField14: TIntegerField;
    DateField8: TDateField;
    WideStringField23: TWideStringField;
    WideStringField27: TWideStringField;
    WideStringField28: TWideStringField;
    WideStringField29: TWideStringField;
    FloatField38: TFloatField;
    FloatField39: TFloatField;
    FloatField40: TFloatField;
    FloatField41: TFloatField;
    FloatField43: TFloatField;
    FloatField44: TFloatField;
    HpCgHz: TClientDataSet;
    IntegerField15: TIntegerField;
    WideStringField30: TWideStringField;
    WideStringField31: TWideStringField;
    WideStringField32: TWideStringField;
    FloatField45: TFloatField;
    StringField7: TStringField;
    HpCgMx: TClientDataSet;
    WideStringField33: TWideStringField;
    IntegerField16: TIntegerField;
    DateField9: TDateField;
    WideStringField34: TWideStringField;
    WideStringField35: TWideStringField;
    WideStringField36: TWideStringField;
    FloatField49: TFloatField;
    FloatField50: TFloatField;
    FloatField51: TFloatField;
    YwyCgHz: TClientDataSet;
    WideStringField37: TWideStringField;
    StringField8: TStringField;
    YwyCgMx: TClientDataSet;
    WideStringField38: TWideStringField;
    IntegerField17: TIntegerField;
    DateField10: TDateField;
    WideStringField39: TWideStringField;
    WideStringField40: TWideStringField;
    WideStringField41: TWideStringField;
    sGysGhHz: TDataSource;
    sGysGhMx: TDataSource;
    sHpCgHz: TDataSource;
    sHpCgMx: TDataSource;
    sYwyCgHz: TDataSource;
    sYwyCgMx: TDataSource;
    CgddQk: TClientDataSet;
    IntegerField18: TIntegerField;
    DateField11: TDateField;
    WideStringField42: TWideStringField;
    WideStringField43: TWideStringField;
    WideStringField44: TWideStringField;
    FloatField61: TFloatField;
    WideStringField45: TWideStringField;
    CgMfDj: TClientDataSet;
    IntegerField19: TIntegerField;
    DateField12: TDateField;
    WideStringField46: TWideStringField;
    WideStringField47: TWideStringField;
    WideStringField48: TWideStringField;
    FloatField62: TFloatField;
    FloatField63: TFloatField;
    FloatField64: TFloatField;
    sCgddQk: TDataSource;
    sCgMfDj: TDataSource;
    HpCgHzJEA: TFloatField;
    HpCgHzJEB: TFloatField;
    HpCgHzJEC: TFloatField;
    HpCgMxJEA: TFloatField;
    HpCgMxJEB: TFloatField;
    HpCgMxJEC: TFloatField;
    YwyCgHzJEA: TFloatField;
    YwyCgHzJEB: TFloatField;
    YwyCgHzJEC: TFloatField;
    YwyCgMxJEA: TFloatField;
    YwyCgMxJEB: TFloatField;
    YwyCgMxJEC: TFloatField;
    CkkcMx: TClientDataSet;
    CkkcHz: TClientDataSet;
    IntegerField20: TIntegerField;
    WideStringField49: TWideStringField;
    WideStringField50: TWideStringField;
    WideStringField51: TWideStringField;
    FloatField46: TFloatField;
    FloatField47: TFloatField;
    CkkcHzSLA: TFloatField;
    CkkcHzJEA: TFloatField;
    CkkcHzSLA2: TFloatField;
    CkkcHzJEA2: TFloatField;
    CkkcHzSLB: TFloatField;
    CkkcHzJEB: TFloatField;
    sCkkcHz: TDataSource;
    sCkkcMx: TDataSource;
    CkkcMxLX: TWideStringField;
    CkkcMxZBID: TIntegerField;
    CkkcMxRQ: TDateField;
    CkkcMxDJBH: TWideStringField;
    CkkcMxPM: TWideStringField;
    CkkcMxSL: TFloatField;
    CkkcMxDJ: TFloatField;
    CkkcMxJEA: TFloatField;
    HpCwb: TClientDataSet;
    sHpCwb: TDataSource;
    YfkZb: TClientDataSet;
    YfkZlfx: TClientDataSet;
    YskZb: TClientDataSet;
    YskZlfx: TClientDataSet;
    sYfkZb: TDataSource;
    sYfkZlfx: TDataSource;
    sYskZb: TDataSource;
    sYskZlfx: TDataSource;
    YskZbID: TIntegerField;
    YskZbBH: TWideStringField;
    YskZbMC: TWideStringField;
    YskZbJEA: TFloatField;
    YskZbJEB: TFloatField;
    YskZbJEC: TFloatField;
    YskZbJEC2: TFloatField;
    YskMx: TClientDataSet;
    sYskMx: TDataSource;
    YfkMx: TClientDataSet;
    sYfkMx: TDataSource;
    YskZbcMC: TStringField;
    YskMxLX: TWideStringField;
    YskMxZBID: TIntegerField;
    YskMxRQ: TDateField;
    YskMxDJBH: TWideStringField;
    YskMxJEB: TFloatField;
    YskMxJEC: TFloatField;
    YskMxJED: TFloatField;
    YskZlfxID: TIntegerField;
    YskZlfxBH: TWideStringField;
    YskZlfxMC: TWideStringField;
    YskZlfxTS1: TFloatField;
    YskZlfxTS2: TFloatField;
    YskZlfxTS3: TFloatField;
    YskZlfxTS4: TFloatField;
    YskZlfxTS5: TFloatField;
    YskZlfxTS6: TFloatField;
    YskZlfxTS7: TFloatField;
    YskZlfxTS8: TFloatField;
    YskZlfxHJ: TFloatField;
    YskZlMx: TClientDataSet;
    IntegerField21: TIntegerField;
    DateField13: TDateField;
    WideStringField53: TWideStringField;
    FloatField48: TFloatField;
    FloatField52: TFloatField;
    FloatField53: TFloatField;
    sYskZlMx: TDataSource;
    YfkZlMx: TClientDataSet;
    sYfkZlMx: TDataSource;
    YskZlMxJEA: TFloatField;
    YfkZbID: TIntegerField;
    YfkZbBH: TWideStringField;
    YfkZbMC: TWideStringField;
    YfkZbJEA: TFloatField;
    YfkZbJEB: TFloatField;
    YfkZbJEC: TFloatField;
    YfkZbJED: TFloatField;
    YfkZbcMC: TStringField;
    YfkMxZBID: TIntegerField;
    YfkMxRQ: TDateField;
    YfkMxLX: TWideStringField;
    YfkMxDJBH: TWideStringField;
    YfkMxJEA: TFloatField;
    YfkMxJEB: TFloatField;
    YfkMxJYJE: TFloatField;
    YfkZlfxID: TIntegerField;
    YfkZlfxBH: TWideStringField;
    YfkZlfxMC: TWideStringField;
    YfkZlfxTS1: TFloatField;
    YfkZlfxTS2: TFloatField;
    YfkZlfxTS3: TFloatField;
    YfkZlfxTS4: TFloatField;
    YfkZlfxTS5: TFloatField;
    YfkZlfxTS6: TFloatField;
    YfkZlfxTS7: TFloatField;
    YfkZlfxTS8: TFloatField;
    YfkZlfxHJ: TFloatField;
    YfkZlMxZBID: TIntegerField;
    YfkZlMxRQ: TDateField;
    YfkZlMxTS: TFloatField;
    YfkZlMxDJBH: TWideStringField;
    YfkZlMxJEA: TFloatField;
    YfkZlMxJEB: TFloatField;
    YfkZlMxJEC: TFloatField;
    ZlFxt: TClientDataSet;
    FloatField55: TFloatField;
    sZlfxt: TDataSource;
    ZlFxtMC: TWideStringField;
    ZlFxtcMC: TStringField;
    RqLsz: TClientDataSet;
    GysLsz: TClientDataSet;
    sRqLsz: TDataSource;
    sGysLsz: TDataSource;
    KhLsz: TClientDataSet;
    sKhLsz: TDataSource;
    SzLsz: TClientDataSet;
    IntegerField23: TIntegerField;
    DateField15: TDateField;
    WideStringField59: TWideStringField;
    FloatField76: TFloatField;
    FloatField77: TFloatField;
    sSzLsz: TDataSource;
    RqLszLX: TWideStringField;
    RqLszZBID: TIntegerField;
    RqLszRQ: TDateField;
    RqLszDJBH: TWideStringField;
    RqLszMC: TWideStringField;
    RqLszJEA: TFloatField;
    RqLszMC1: TWideStringField;
    KhLszLX: TWideStringField;
    KhLszID: TIntegerField;
    KhLszRQ: TDateField;
    KhLszDJBH: TWideStringField;
    KhLszJE: TFloatField;
    KhLszBZ: TWideStringField;
    GysLszLX: TWideStringField;
    GysLszID: TIntegerField;
    GysLszRQ: TDateField;
    GysLszDJBH: TWideStringField;
    GysLszJE: TFloatField;
    GysLszBZ: TWideStringField;
    CkLsz: TClientDataSet;
    IntegerField1: TIntegerField;
    DateField14: TDateField;
    WideStringField52: TWideStringField;
    sCkLsz: TDataSource;
    CkLszBH: TWideStringField;
    CkLszPM: TWideStringField;
    CkLszDW: TWideStringField;
    CkLszSL1: TFloatField;
    CkLszDJ1: TFloatField;
    CkLszJE1: TFloatField;
    CkLszLX: TWideStringField;
    SzLszLX: TWideStringField;
    SzLszBZ: TWideStringField;
    SzLszBZ2: TWideStringField;
    SzLszBZ3: TWideStringField;
    YyqkHz: TClientDataSet;
    IntegerField2: TIntegerField;
    WideStringField54: TWideStringField;
    WideStringField55: TWideStringField;
    FloatField54: TFloatField;
    FloatField56: TFloatField;
    FloatField57: TFloatField;
    FloatField58: TFloatField;
    StringField9: TStringField;
    SzHz: TClientDataSet;
    IntegerField22: TIntegerField;
    WideStringField56: TWideStringField;
    WideStringField57: TWideStringField;
    FloatField59: TFloatField;
    FloatField60: TFloatField;
    XjyhHz: TClientDataSet;
    IntegerField24: TIntegerField;
    WideStringField58: TWideStringField;
    WideStringField60: TWideStringField;
    sYyqkHz: TDataSource;
    sSzHz: TDataSource;
    sXjyhHz: TDataSource;
    SzMx: TClientDataSet;
    IntegerField25: TIntegerField;
    DateField16: TDateField;
    WideStringField61: TWideStringField;
    WideStringField62: TWideStringField;
    FloatField78: TFloatField;
    FloatField79: TFloatField;
    sSzMx: TDataSource;
    XjyhMx: TClientDataSet;
    IntegerField26: TIntegerField;
    DateField17: TDateField;
    WideStringField63: TWideStringField;
    FloatField82: TFloatField;
    FloatField83: TFloatField;
    sXjyhMx: TDataSource;
    XjyhHzJEA: TFloatField;
    XjyhHzJEB: TFloatField;
    XjyhHzJEC: TFloatField;
    XjyhHzJED: TFloatField;
    XjyhHzcMC: TStringField;
    XjyhMxLX: TWideStringField;
    XjyhMxJYJE: TFloatField;
    CkkcMxSL1: TFloatField;
    CkkcMxJE1: TFloatField;
    CkkcMxSL12: TFloatField;
    CkkcMxJE12: TFloatField;
    Yylrb: TClientDataSet;
    JdqYsk: TClientDataSet;
    sYylrb: TDataSource;
    sJdqYsk: TDataSource;
    CqYsk: TClientDataSet;
    IntegerField29: TIntegerField;
    DateField20: TDateField;
    WideStringField72: TWideStringField;
    FloatField67: TFloatField;
    sCqYsk: TDataSource;
    JdqYfk: TClientDataSet;
    sJdqYfk: TDataSource;
    CqYfk: TClientDataSet;
    sCqYfk: TDataSource;
    CqYskBH: TWideStringField;
    CqYskMC: TWideStringField;
    CqYskQFJE: TFloatField;
    CqYskQFJE2: TFloatField;
    CqYfkID: TIntegerField;
    CqYfkDJBH: TWideStringField;
    CqYfkBH: TWideStringField;
    CqYfkMC: TWideStringField;
    CqYfkXDRQ: TDateField;
    CqYfkJE: TFloatField;
    CqYfkYSJE: TFloatField;
    CqYfkMSJE: TFloatField;
    JdqYskID: TIntegerField;
    JdqYskDJBH: TWideStringField;
    JdqYskBH: TWideStringField;
    JdqYskMC: TWideStringField;
    JdqYskXDRQ: TDateField;
    JdqYskJE: TFloatField;
    JdqYskYSJE: TFloatField;
    JdqYskMSJE: TFloatField;
    JdqYfkID: TIntegerField;
    JdqYfkDJBH: TWideStringField;
    JdqYfkBH: TWideStringField;
    JdqYfkMC: TWideStringField;
    JdqYfkXDRQ: TDateField;
    JdqYfkJE: TFloatField;
    JdqYfkYSJE: TFloatField;
    JdqYfkMSJE: TFloatField;
    YylrbYF: TIntegerField;
    YylrbJEA: TFloatField;
    YylrbCBJE: TFloatField;
    YylrbLRJE: TFloatField;
    YylrbLRJE2: TFloatField;
    YylrbLRJE3: TFloatField;
    YylrbLRJE4: TFloatField;
    procedure NSLGetText(Sender: TField; var Text: String;
      DisplayText: Boolean);
    procedure CalcFields_MC(DataSet: TDataSet);
    procedure CalcFields_PM(DataSet: TDataSet);
    procedure CalcFields_YWY(DataSet: TDataSet);
    procedure ZeroToEmpty(Sender: TField; var Text: String;
      DisplayText: Boolean);
    procedure YWYGetText(Sender: TField; var Text: String;
      DisplayText: Boolean);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  DataBb: TDataBb;

implementation

uses Dm;

{$R *.DFM}

//税率
procedure TDataBb.NSLGetText(Sender: TField; var Text: String;
  DisplayText: Boolean);
begin
  Text := Sender.AsString + '%';
end;

//Set cMC (用于分析图)
procedure TDataBb.CalcFields_MC(DataSet: TDataSet);
begin
  DataSet['cMC'] := DataSet['MC'];
end;

procedure TDataBb.CalcFields_PM(DataSet: TDataSet);
begin
  DataSet['cPM'] := DataSet['PM'];
end;

procedure TDataBb.CalcFields_YWY(DataSet: TDataSet);
begin
  DataSet['cYWY'] := DataSet['YWY'];
end;

procedure TDataBb.YWYGetText(Sender: TField; var Text: String;
  DisplayText: Boolean);
begin
  if Sender.AsString = '' then
    Text := '其他'
  else
    Text := Sender.AsString;
end;

procedure TDataBb.ZeroToEmpty(Sender: TField; var Text: String;
  DisplayText: Boolean);
begin
  if Sender is TNumericField then
    if TField(Sender).AsFloat = 0 then
      Text := ''
    else
      Text := FormatFloat(TFloatField(Sender).DisplayFormat, TField(Sender).Value);
end;

end.
