object frmCMain: TfrmCMain
  Left = 110
  Top = 183
  BorderIcons = [biSystemMenu, biMinimize]
  BorderStyle = bsSingle
  Caption = 'frmCMain'
  ClientHeight = 504
  ClientWidth = 792
  Color = clBtnFace
  Font.Charset = GB2312_CHARSET
  Font.Color = clWindowText
  Font.Height = -12
  Font.Name = #23435#20307
  Font.Style = []
  Menu = MainMenu1
  OldCreateOrder = False
  Position = poDesktopCenter
  Visible = True
  OnClose = FormClose
  OnCloseQuery = FormCloseQuery
  OnCreate = FormCreate
  OnDestroy = FormDestroy
  PixelsPerInch = 96
  TextHeight = 12
  object StatusBar: TStatusBar
    Left = 0
    Top = 485
    Width = 792
    Height = 19
    Panels = <
      item
        Width = 180
      end
      item
        Width = 200
      end>
  end
  object PanelMenu: TPanel
    Left = 0
    Top = 73
    Width = 137
    Height = 412
    Align = alLeft
    BevelOuter = bvLowered
    TabOrder = 1
    object ListBoxActor: TListBox
      Left = 1
      Top = 1
      Width = 135
      Height = 410
      Style = lbOwnerDrawVariable
      Align = alClient
      Color = clMoneyGreen
      ItemHeight = 12
      TabOrder = 0
      OnClick = ListBoxActorDblClick
      OnDrawItem = ListBoxActorDrawItem
    end
  end
  object PanelTitle: TPanel
    Left = 0
    Top = 0
    Width = 792
    Height = 73
    Align = alTop
    BevelOuter = bvLowered
    TabOrder = 2
  end
  object PanelClient: TPanel
    Left = 137
    Top = 73
    Width = 655
    Height = 412
    Align = alClient
    BevelOuter = bvLowered
    TabOrder = 3
    object PanelSelectServer: TPanel
      Left = 528
      Top = 176
      Width = 281
      Height = 361
      Color = clTeal
      TabOrder = 0
      Visible = False
      OnMouseDown = PanelUserLoginMouseDown
      object ButtonSelectServerClose: TSpeedButton
        Left = 256
        Top = 8
        Width = 17
        Height = 25
        Caption = 'X'
        Flat = True
        OnClick = ButtonStartClick
      end
      object ButtonServer1: TRzButton
        Left = 64
        Top = 24
        Width = 161
        Height = 33
        Font.Charset = GB2312_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = #23435#20307
        Font.Style = [fsBold]
        HotTrack = True
        ParentFont = False
        TabOrder = 0
        OnClick = ButtonServer1Click
      end
      object ButtonServer2: TRzButton
        Left = 64
        Top = 64
        Width = 161
        Height = 33
        Font.Charset = GB2312_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = #23435#20307
        Font.Style = [fsBold]
        HotTrack = True
        ParentFont = False
        TabOrder = 1
        OnClick = ButtonServer1Click
      end
      object ButtonServer3: TRzButton
        Left = 64
        Top = 104
        Width = 161
        Height = 33
        Font.Charset = GB2312_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = #23435#20307
        Font.Style = [fsBold]
        HotTrack = True
        ParentFont = False
        TabOrder = 2
        OnClick = ButtonServer1Click
      end
      object ButtonServer4: TRzButton
        Left = 64
        Top = 144
        Width = 161
        Height = 33
        Font.Charset = GB2312_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = #23435#20307
        Font.Style = [fsBold]
        HotTrack = True
        ParentFont = False
        TabOrder = 3
        OnClick = ButtonServer1Click
      end
      object ButtonServer5: TRzButton
        Left = 64
        Top = 184
        Width = 161
        Height = 33
        Font.Charset = GB2312_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = #23435#20307
        Font.Style = [fsBold]
        HotTrack = True
        ParentFont = False
        TabOrder = 4
        OnClick = ButtonServer1Click
      end
      object ButtonServer6: TRzButton
        Left = 64
        Top = 224
        Width = 161
        Height = 33
        Font.Charset = GB2312_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = #23435#20307
        Font.Style = [fsBold]
        HotTrack = True
        ParentFont = False
        TabOrder = 5
        OnClick = ButtonServer1Click
      end
      object ButtonServer7: TRzButton
        Left = 64
        Top = 264
        Width = 161
        Height = 33
        Font.Charset = GB2312_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = #23435#20307
        Font.Style = [fsBold]
        HotTrack = True
        ParentFont = False
        TabOrder = 6
        OnClick = ButtonServer1Click
      end
      object ButtonServer8: TRzButton
        Left = 64
        Top = 304
        Width = 161
        Height = 33
        Font.Charset = GB2312_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = #23435#20307
        Font.Style = [fsBold]
        HotTrack = True
        ParentFont = False
        TabOrder = 7
        OnClick = ButtonServer1Click
      end
    end
    object PanelSelectChr: TPanel
      Left = 568
      Top = 72
      Width = 609
      Height = 369
      Color = clTeal
      TabOrder = 1
      Visible = False
      object ButtonSelectChrClose: TSpeedButton
        Left = 584
        Top = 8
        Width = 17
        Height = 25
        Caption = 'X'
        Flat = True
        OnClick = ButtonStartClick
      end
      object GroupBox1: TGroupBox
        Left = 8
        Top = 224
        Width = 193
        Height = 129
        Caption = #20154#29289#19968
        TabOrder = 0
        object Label3: TLabel
          Left = 8
          Top = 52
          Width = 30
          Height = 12
          Caption = #21517#31216':'
        end
        object Label4: TLabel
          Left = 8
          Top = 100
          Width = 30
          Height = 12
          Caption = #32844#19994':'
        end
        object Label5: TLabel
          Left = 8
          Top = 76
          Width = 30
          Height = 12
          Caption = #31561#32423':'
        end
        object Label6: TLabel
          Left = 96
          Top = 76
          Width = 30
          Height = 12
          Caption = #24615#21035':'
        end
        object EditSelectChrName1: TEdit
          Left = 40
          Top = 48
          Width = 137
          Height = 20
          BevelKind = bkFlat
          BorderStyle = bsNone
          Enabled = False
          TabOrder = 0
          OnKeyPress = EditUserAccountKeyPress
        end
        object EditSelectChrJob1: TEdit
          Left = 40
          Top = 96
          Width = 137
          Height = 20
          BevelKind = bkFlat
          BorderStyle = bsNone
          Enabled = False
          TabOrder = 1
          OnKeyPress = EditUserAccountKeyPress
        end
        object EditSelectChrLevel1: TEdit
          Left = 40
          Top = 72
          Width = 49
          Height = 20
          BevelKind = bkFlat
          BorderStyle = bsNone
          Enabled = False
          TabOrder = 2
          OnKeyPress = EditUserAccountKeyPress
        end
        object EditSelectChrSex1: TEdit
          Left = 128
          Top = 72
          Width = 49
          Height = 20
          BevelKind = bkFlat
          BorderStyle = bsNone
          Enabled = False
          TabOrder = 3
          OnKeyPress = EditUserAccountKeyPress
        end
        object ButtonSelectChr1: TRzButton
          Left = 102
          Top = 16
          Caption = #36873#25321
          HotTrack = True
          TabOrder = 4
          OnClick = ButtonSelectChr1Click
        end
      end
      object GroupBox2: TGroupBox
        Left = 408
        Top = 224
        Width = 193
        Height = 129
        Caption = #20154#29289#20108
        TabOrder = 1
        object Label7: TLabel
          Left = 8
          Top = 52
          Width = 30
          Height = 12
          Caption = #21517#31216':'
        end
        object Label8: TLabel
          Left = 8
          Top = 100
          Width = 30
          Height = 12
          Caption = #32844#19994':'
        end
        object Label9: TLabel
          Left = 8
          Top = 76
          Width = 30
          Height = 12
          Caption = #31561#32423':'
        end
        object Label10: TLabel
          Left = 96
          Top = 76
          Width = 30
          Height = 12
          Caption = #24615#21035':'
        end
        object EditSelectChrName2: TEdit
          Left = 40
          Top = 48
          Width = 137
          Height = 20
          BevelKind = bkFlat
          BorderStyle = bsNone
          Enabled = False
          TabOrder = 0
          OnKeyPress = EditUserAccountKeyPress
        end
        object EditSelectChrJob2: TEdit
          Left = 40
          Top = 96
          Width = 137
          Height = 20
          BevelKind = bkFlat
          BorderStyle = bsNone
          Enabled = False
          TabOrder = 1
          OnKeyPress = EditUserAccountKeyPress
        end
        object EditSelectChrLevel2: TEdit
          Left = 40
          Top = 72
          Width = 49
          Height = 20
          BevelKind = bkFlat
          BorderStyle = bsNone
          Enabled = False
          TabOrder = 2
          OnKeyPress = EditUserAccountKeyPress
        end
        object EditSelectChrSex2: TEdit
          Left = 128
          Top = 72
          Width = 49
          Height = 20
          BevelKind = bkFlat
          BorderStyle = bsNone
          Enabled = False
          TabOrder = 3
          OnKeyPress = EditUserAccountKeyPress
        end
        object ButtonSelectChr2: TRzButton
          Left = 102
          Top = 16
          Caption = #36873#25321
          HotTrack = True
          TabOrder = 4
          OnClick = ButtonSelectChr1Click
        end
      end
      object GroupBox3: TGroupBox
        Left = 208
        Top = 224
        Width = 193
        Height = 129
        TabOrder = 2
        object EditSelectChrCurChr: TEdit
          Left = 32
          Top = 96
          Width = 129
          Height = 20
          BevelKind = bkFlat
          BorderStyle = bsNone
          Enabled = False
          TabOrder = 0
          OnKeyPress = EditUserAccountKeyPress
        end
        object ButtonSelectChrStartPlay: TRzButton
          Left = 32
          Top = 16
          Width = 129
          Caption = #24320#22987#28216#25103
          HotTrack = True
          TabOrder = 1
          OnClick = ButtonSelectChr1Click
        end
        object ButtonSelectChrNewChr: TRzButton
          Left = 32
          Top = 40
          Width = 129
          Caption = #26032#24314#20154#29289
          HotTrack = True
          TabOrder = 2
          OnClick = ButtonSelectChr1Click
        end
        object ButtonSelectChrDelChr: TRzButton
          Left = 32
          Top = 64
          Width = 129
          Caption = #21024#38500#20154#29289
          HotTrack = True
          TabOrder = 3
          OnClick = ButtonSelectChr1Click
        end
      end
      object PanelCreateNewChr: TPanel
        Left = 88
        Top = 16
        Width = 377
        Height = 193
        Color = clOlive
        TabOrder = 3
        Visible = False
        object ButtonCreateNewChr: TSpeedButton
          Left = 352
          Top = 8
          Width = 17
          Height = 25
          Caption = 'X'
          Flat = True
          OnClick = ButtonStartClick
        end
        object GroupBox4: TGroupBox
          Left = 200
          Top = 40
          Width = 169
          Height = 137
          TabOrder = 0
          object ButtonCreateNewChrWarr: TRzButton
            Left = 14
            Top = 24
            Width = 43
            Caption = #27494#22763
            HotTrack = True
            TabOrder = 0
            OnClick = ButtonSelectChr1Click
          end
          object ButtonCreateNewChrWizard: TRzButton
            Left = 62
            Top = 24
            Width = 43
            Caption = #27861#24072
            HotTrack = True
            TabOrder = 1
            OnClick = ButtonSelectChr1Click
          end
          object ButtonCreateNewChrTaos: TRzButton
            Left = 110
            Top = 24
            Width = 43
            Caption = #36947#22763
            HotTrack = True
            TabOrder = 2
            OnClick = ButtonSelectChr1Click
          end
          object ButtonCreateNewChrFemale: TRzButton
            Left = 94
            Top = 64
            Width = 43
            Caption = #22899
            HotTrack = True
            TabOrder = 3
            OnClick = ButtonSelectChr1Click
          end
          object ButtonCreateNewChrMale: TRzButton
            Left = 38
            Top = 64
            Width = 43
            Caption = #30007
            HotTrack = True
            TabOrder = 4
            OnClick = ButtonSelectChr1Click
          end
          object ButtonCreateNewChrOK: TRzButton
            Left = 48
            Top = 104
            Width = 65
            Caption = #30830#23450
            HotTrack = True
            TabOrder = 5
            OnClick = ButtonSelectChr1Click
          end
        end
        object GroupBox5: TGroupBox
          Left = 8
          Top = 40
          Width = 185
          Height = 137
          Caption = #20154#29289#20449#24687
          TabOrder = 1
          object Label11: TLabel
            Left = 8
            Top = 20
            Width = 30
            Height = 12
            Caption = #21517#31216':'
          end
          object Label13: TLabel
            Left = 8
            Top = 44
            Width = 30
            Height = 12
            Caption = #24615#21035':'
          end
          object Label14: TLabel
            Left = 8
            Top = 68
            Width = 30
            Height = 12
            Caption = #32844#19994':'
          end
          object EditCreateNewChrName: TEdit
            Left = 40
            Top = 16
            Width = 137
            Height = 20
            BevelKind = bkFlat
            BorderStyle = bsNone
            TabOrder = 0
            OnKeyPress = EditUserAccountKeyPress
          end
          object EditCreateNewChrSex: TEdit
            Left = 40
            Top = 40
            Width = 137
            Height = 20
            BevelKind = bkFlat
            BorderStyle = bsNone
            Enabled = False
            TabOrder = 1
            OnKeyPress = EditUserAccountKeyPress
          end
          object EditCreateNewChrJob: TEdit
            Left = 40
            Top = 64
            Width = 137
            Height = 20
            BevelKind = bkFlat
            BorderStyle = bsNone
            Enabled = False
            TabOrder = 2
            OnKeyPress = EditUserAccountKeyPress
          end
        end
      end
    end
    object PanelPlayGame: TPanel
      Left = 1
      Top = 1
      Width = 678
      Height = 410
      TabOrder = 2
      Visible = False
      object Panel1: TPanel
        Left = 1
        Top = 266
        Width = 676
        Height = 143
        Align = alBottom
        BevelOuter = bvLowered
        Caption = 'Panel1'
        TabOrder = 0
        object SpeedButton2: TSpeedButton
          Left = 483
          Top = 14
          Width = 38
          Height = 22
          Caption = #35013#22791
          Flat = True
          Font.Charset = GB2312_CHARSET
          Font.Color = clBlue
          Font.Height = -12
          Font.Name = #23435#20307
          Font.Style = []
          ParentFont = False
        end
        object SpeedButton3: TSpeedButton
          Left = 523
          Top = 14
          Width = 38
          Height = 22
          Caption = #32972#21253
          Flat = True
          Font.Charset = GB2312_CHARSET
          Font.Color = clBlue
          Font.Height = -12
          Font.Name = #23435#20307
          Font.Style = []
          ParentFont = False
        end
        object SpeedButton4: TSpeedButton
          Left = 563
          Top = 14
          Width = 38
          Height = 22
          Caption = #25216#33021
          Flat = True
          Font.Charset = GB2312_CHARSET
          Font.Color = clBlue
          Font.Height = -12
          Font.Name = #23435#20307
          Font.Style = []
          ParentFont = False
        end
        object SpeedButton5: TSpeedButton
          Left = 603
          Top = 14
          Width = 38
          Height = 22
          Caption = #36873#39033
          Flat = True
          Font.Charset = GB2312_CHARSET
          Font.Color = clBlue
          Font.Height = -12
          Font.Name = #23435#20307
          Font.Style = []
          ParentFont = False
        end
        object SpeedButton6: TSpeedButton
          Left = 483
          Top = 38
          Width = 38
          Height = 22
          Caption = #22320#22270
          Flat = True
          Font.Charset = GB2312_CHARSET
          Font.Color = clBlue
          Font.Height = -12
          Font.Name = #23435#20307
          Font.Style = []
          ParentFont = False
        end
        object SpeedButton7: TSpeedButton
          Left = 523
          Top = 38
          Width = 38
          Height = 22
          Caption = #20132#26131
          Flat = True
          Font.Charset = GB2312_CHARSET
          Font.Color = clBlue
          Font.Height = -12
          Font.Name = #23435#20307
          Font.Style = []
          ParentFont = False
        end
        object SpeedButton8: TSpeedButton
          Left = 563
          Top = 38
          Width = 38
          Height = 22
          Caption = #34892#20250
          Flat = True
          Font.Charset = GB2312_CHARSET
          Font.Color = clBlue
          Font.Height = -12
          Font.Name = #23435#20307
          Font.Style = []
          ParentFont = False
        end
        object SpeedButton9: TSpeedButton
          Left = 603
          Top = 38
          Width = 38
          Height = 22
          Caption = #32452#38431
          Flat = True
          Font.Charset = GB2312_CHARSET
          Font.Color = clBlue
          Font.Height = -12
          Font.Name = #23435#20307
          Font.Style = []
          ParentFont = False
        end
        object SpeedButton13: TSpeedButton
          Left = 603
          Top = 62
          Width = 38
          Height = 22
          Caption = #36873#39033
          Flat = True
          Font.Charset = GB2312_CHARSET
          Font.Color = clBlue
          Font.Height = -12
          Font.Name = #23435#20307
          Font.Style = []
          ParentFont = False
        end
        object SpeedButton17: TSpeedButton
          Left = 603
          Top = 86
          Width = 38
          Height = 22
          Caption = #23567#36864
          Flat = True
          Font.Charset = GB2312_CHARSET
          Font.Color = clBlue
          Font.Height = -12
          Font.Name = #23435#20307
          Font.Style = []
          ParentFont = False
        end
        object ButtonPlayGameClose: TSpeedButton
          Left = 603
          Top = 110
          Width = 38
          Height = 22
          Caption = #36864#20986
          Flat = True
          Font.Charset = GB2312_CHARSET
          Font.Color = clBlue
          Font.Height = -12
          Font.Name = #23435#20307
          Font.Style = []
          ParentFont = False
          OnClick = ButtonStartClick
        end
        object LabelPlayGameHP: TLabel
          Left = 483
          Top = 64
          Width = 110
          Height = 12
          AutoSize = False
          Caption = 'LabelPlayGameHP'
          Font.Charset = GB2312_CHARSET
          Font.Color = clRed
          Font.Height = -12
          Font.Name = #23435#20307
          Font.Style = []
          ParentFont = False
        end
        object LabelPlayGameMP: TLabel
          Left = 483
          Top = 80
          Width = 110
          Height = 12
          AutoSize = False
          Caption = 'LabelPlayGameHP'
          Font.Charset = GB2312_CHARSET
          Font.Color = clBlue
          Font.Height = -12
          Font.Name = #23435#20307
          Font.Style = []
          ParentFont = False
        end
        object LabelPlayGameLevel: TLabel
          Left = 483
          Top = 96
          Width = 110
          Height = 12
          AutoSize = False
          Caption = 'LabelPlayGameLevel'
          Font.Charset = GB2312_CHARSET
          Font.Color = clTeal
          Font.Height = -12
          Font.Name = #23435#20307
          Font.Style = []
          ParentFont = False
        end
        object EditChat: TEdit
          Left = 0
          Top = 121
          Width = 473
          Height = 20
          TabOrder = 0
          OnKeyPress = EditChatKeyPress
        end
        object ListBoxChat: TListBox
          Left = 0
          Top = 0
          Width = 473
          Height = 121
          Style = lbOwnerDrawVariable
          ItemHeight = 16
          PopupMenu = PopupMenu
          TabOrder = 1
          OnClick = ListBoxChatClick
          OnDblClick = ListBoxChatDblClick
          OnDrawItem = ListBoxActorDrawItem
        end
      end
      object PanelPlay: TPanel
        Left = 97
        Top = 1
        Width = 676
        Height = 265
        BevelOuter = bvNone
        TabOrder = 1
      end
    end
    object PanelNewAccount: TPanel
      Left = 0
      Top = -8
      Width = 473
      Height = 321
      Color = clOlive
      TabOrder = 3
      Visible = False
      OnMouseDown = PanelUserLoginMouseDown
      object ButtonPanelNewAccountClose: TSpeedButton
        Left = 448
        Top = 8
        Width = 17
        Height = 25
        Caption = 'X'
        Flat = True
        OnClick = ButtonStartClick
      end
      object LabelStatus: TLabel
        Left = 97
        Top = 304
        Width = 6
        Height = 12
      end
      object GroupBox6: TGroupBox
        Left = 24
        Top = 16
        Width = 417
        Height = 289
        Caption = #24080#21495#20449#24687
        TabOrder = 0
        object Label15: TLabel
          Left = 8
          Top = 20
          Width = 54
          Height = 12
          Caption = #30331#24405#24080#21495':'
          Font.Charset = GB2312_CHARSET
          Font.Color = clRed
          Font.Height = -12
          Font.Name = #23435#20307
          Font.Style = []
          ParentFont = False
        end
        object Label16: TLabel
          Left = 8
          Top = 44
          Width = 54
          Height = 12
          Caption = #29992#25143#23494#30721':'
          Font.Charset = GB2312_CHARSET
          Font.Color = clRed
          Font.Height = -12
          Font.Name = #23435#20307
          Font.Style = []
          ParentFont = False
        end
        object Label17: TLabel
          Left = 8
          Top = 68
          Width = 54
          Height = 12
          Caption = #30830#35748#23494#30721':'
          Font.Charset = GB2312_CHARSET
          Font.Color = clRed
          Font.Height = -12
          Font.Name = #23435#20307
          Font.Style = []
          ParentFont = False
        end
        object Label18: TLabel
          Left = 8
          Top = 92
          Width = 54
          Height = 12
          Caption = #29992#25143#21517#31216':'
          Font.Charset = GB2312_CHARSET
          Font.Color = clRed
          Font.Height = -12
          Font.Name = #23435#20307
          Font.Style = []
          ParentFont = False
        end
        object Label19: TLabel
          Left = 8
          Top = 116
          Width = 54
          Height = 12
          Caption = #36523#20221#35777#21495':'
          Font.Charset = GB2312_CHARSET
          Font.Color = clRed
          Font.Height = -12
          Font.Name = #23435#20307
          Font.Style = []
          ParentFont = False
        end
        object Label20: TLabel
          Left = 8
          Top = 140
          Width = 54
          Height = 12
          Caption = #20986#29983#26085#26399':'
          Font.Charset = GB2312_CHARSET
          Font.Color = clRed
          Font.Height = -12
          Font.Name = #23435#20307
          Font.Style = []
          ParentFont = False
        end
        object Label21: TLabel
          Left = 8
          Top = 164
          Width = 42
          Height = 12
          Caption = #38382#39064#19968':'
          Font.Charset = GB2312_CHARSET
          Font.Color = clRed
          Font.Height = -12
          Font.Name = #23435#20307
          Font.Style = []
          ParentFont = False
        end
        object Label22: TLabel
          Left = 8
          Top = 188
          Width = 42
          Height = 12
          Caption = #31572#26696#19968':'
          Font.Charset = GB2312_CHARSET
          Font.Color = clRed
          Font.Height = -12
          Font.Name = #23435#20307
          Font.Style = []
          ParentFont = False
        end
        object Label23: TLabel
          Left = 8
          Top = 236
          Width = 42
          Height = 12
          Caption = #31572#26696#20108':'
          Font.Charset = GB2312_CHARSET
          Font.Color = clRed
          Font.Height = -12
          Font.Name = #23435#20307
          Font.Style = []
          ParentFont = False
        end
        object Label24: TLabel
          Left = 8
          Top = 212
          Width = 42
          Height = 12
          Caption = #38382#39064#20108':'
          Font.Charset = GB2312_CHARSET
          Font.Color = clRed
          Font.Height = -12
          Font.Name = #23435#20307
          Font.Style = []
          ParentFont = False
        end
        object Label25: TLabel
          Left = 208
          Top = 164
          Width = 54
          Height = 12
          Caption = #32852#31995#30005#35805':'
        end
        object Label26: TLabel
          Left = 208
          Top = 188
          Width = 54
          Height = 12
          Caption = #25163#26426#21495#30721':'
        end
        object Label27: TLabel
          Left = 8
          Top = 260
          Width = 54
          Height = 12
          Caption = #37038#31665#22320#22336':'
        end
        object Label28: TLabel
          Left = 216
          Top = 220
          Width = 180
          Height = 29
          AutoSize = False
          Caption = #27880#24847#65306#26631#26126#20026#32418#33394#30340#20026#24517#38656#35201#22635#20889#30340#20869#23481#12290
          Font.Charset = GB2312_CHARSET
          Font.Color = clRed
          Font.Height = -12
          Font.Name = #23435#20307
          Font.Style = []
          ParentFont = False
          WordWrap = True
        end
        object EditPassword: TEdit
          Left = 64
          Top = 40
          Width = 89
          Height = 20
          BevelKind = bkFlat
          BevelOuter = bvRaised
          BorderStyle = bsNone
          Font.Charset = GB2312_CHARSET
          Font.Color = clBlue
          Font.Height = -12
          Font.Name = #23435#20307
          Font.Style = []
          MaxLength = 10
          ParentFont = False
          PasswordChar = '*'
          TabOrder = 1
          OnEnter = EditAccountEnter
        end
        object EditAccount: TEdit
          Left = 64
          Top = 16
          Width = 89
          Height = 20
          BevelKind = bkFlat
          BevelOuter = bvRaised
          BorderStyle = bsNone
          Font.Charset = GB2312_CHARSET
          Font.Color = clBlue
          Font.Height = -12
          Font.Name = #23435#20307
          Font.Style = []
          MaxLength = 10
          ParentFont = False
          TabOrder = 0
          OnEnter = EditAccountEnter
        end
        object EditConfirm: TEdit
          Left = 64
          Top = 64
          Width = 89
          Height = 20
          BevelKind = bkFlat
          BevelOuter = bvRaised
          BorderStyle = bsNone
          Font.Charset = GB2312_CHARSET
          Font.Color = clBlue
          Font.Height = -12
          Font.Name = #23435#20307
          Font.Style = []
          MaxLength = 10
          ParentFont = False
          PasswordChar = '*'
          TabOrder = 2
          OnEnter = EditAccountEnter
        end
        object EditYourName: TEdit
          Left = 64
          Top = 88
          Width = 89
          Height = 20
          BevelKind = bkFlat
          BevelOuter = bvRaised
          BorderStyle = bsNone
          Font.Charset = GB2312_CHARSET
          Font.Color = clBlue
          Font.Height = -12
          Font.Name = #23435#20307
          Font.Style = []
          MaxLength = 10
          ParentFont = False
          TabOrder = 3
          OnEnter = EditAccountEnter
        end
        object EditSSNo: TEdit
          Left = 64
          Top = 112
          Width = 89
          Height = 20
          BevelKind = bkFlat
          BevelOuter = bvRaised
          BorderStyle = bsNone
          Enabled = False
          Font.Charset = GB2312_CHARSET
          Font.Color = clBlue
          Font.Height = -12
          Font.Name = #23435#20307
          Font.Style = []
          MaxLength = 10
          ParentFont = False
          TabOrder = 4
          Text = '0123456'
          OnEnter = EditAccountEnter
        end
        object EditBirthDay: TEdit
          Left = 64
          Top = 136
          Width = 89
          Height = 20
          BevelKind = bkFlat
          BevelOuter = bvRaised
          BorderStyle = bsNone
          Font.Charset = GB2312_CHARSET
          Font.Color = clBlue
          Font.Height = -12
          Font.Name = #23435#20307
          Font.Style = []
          MaxLength = 10
          ParentFont = False
          TabOrder = 5
          OnEnter = EditAccountEnter
        end
        object EditQuiz1: TEdit
          Left = 64
          Top = 160
          Width = 137
          Height = 20
          BevelKind = bkFlat
          BevelOuter = bvRaised
          BorderStyle = bsNone
          Font.Charset = GB2312_CHARSET
          Font.Color = clBlue
          Font.Height = -12
          Font.Name = #23435#20307
          Font.Style = []
          MaxLength = 10
          ParentFont = False
          TabOrder = 6
          OnEnter = EditAccountEnter
        end
        object EditAnswer1: TEdit
          Left = 64
          Top = 184
          Width = 137
          Height = 20
          BevelKind = bkFlat
          BevelOuter = bvRaised
          BorderStyle = bsNone
          Font.Charset = GB2312_CHARSET
          Font.Color = clBlue
          Font.Height = -12
          Font.Name = #23435#20307
          Font.Style = []
          MaxLength = 10
          ParentFont = False
          TabOrder = 7
          OnEnter = EditAccountEnter
        end
        object EditQuiz2: TEdit
          Left = 64
          Top = 208
          Width = 137
          Height = 20
          BevelKind = bkFlat
          BevelOuter = bvRaised
          BorderStyle = bsNone
          Font.Charset = GB2312_CHARSET
          Font.Color = clBlue
          Font.Height = -12
          Font.Name = #23435#20307
          Font.Style = []
          MaxLength = 10
          ParentFont = False
          TabOrder = 8
          OnEnter = EditAccountEnter
        end
        object EditAnswer2: TEdit
          Left = 64
          Top = 232
          Width = 137
          Height = 20
          BevelKind = bkFlat
          BevelOuter = bvRaised
          BorderStyle = bsNone
          Font.Charset = GB2312_CHARSET
          Font.Color = clBlue
          Font.Height = -12
          Font.Name = #23435#20307
          Font.Style = []
          MaxLength = 10
          ParentFont = False
          TabOrder = 9
          OnEnter = EditAccountEnter
        end
        object MemoHelp: TMemo
          Left = 168
          Top = 16
          Width = 241
          Height = 137
          BevelKind = bkFlat
          BevelOuter = bvRaised
          BorderStyle = bsNone
          Ctl3D = True
          Enabled = False
          ParentCtl3D = False
          ReadOnly = True
          TabOrder = 13
        end
        object EditPhone: TEdit
          Left = 264
          Top = 160
          Width = 137
          Height = 20
          BevelKind = bkFlat
          BevelOuter = bvRaised
          BorderStyle = bsNone
          Font.Charset = GB2312_CHARSET
          Font.Color = clBlue
          Font.Height = -12
          Font.Name = #23435#20307
          Font.Style = []
          MaxLength = 10
          ParentFont = False
          TabOrder = 11
          OnEnter = EditAccountEnter
        end
        object EditMobPhone: TEdit
          Left = 264
          Top = 184
          Width = 137
          Height = 20
          BevelKind = bkFlat
          BevelOuter = bvRaised
          BorderStyle = bsNone
          Font.Charset = GB2312_CHARSET
          Font.Color = clBlue
          Font.Height = -12
          Font.Name = #23435#20307
          Font.Style = []
          MaxLength = 10
          ParentFont = False
          TabOrder = 12
          OnEnter = EditAccountEnter
        end
        object EditEMail: TEdit
          Left = 64
          Top = 256
          Width = 137
          Height = 20
          BevelKind = bkFlat
          BevelOuter = bvRaised
          BorderStyle = bsNone
          Font.Charset = GB2312_CHARSET
          Font.Color = clBlue
          Font.Height = -12
          Font.Name = #23435#20307
          Font.Style = []
          MaxLength = 10
          ParentFont = False
          TabOrder = 10
          OnEnter = EditAccountEnter
        end
        object ButtonPanelNewAccountOK: TRzButton
          Left = 320
          Top = 249
          Width = 81
          Height = 33
          Caption = #30830#23450'(&O)'
          HotTrack = True
          TabOrder = 14
          OnClick = ButtonPanelNewAccountOKClick
        end
      end
    end
  end
  object PanelUserLogin: TPanel
    Left = 16
    Top = 224
    Width = 281
    Height = 185
    Color = clTeal
    TabOrder = 4
    Visible = False
    OnMouseDown = PanelUserLoginMouseDown
    object Label1: TLabel
      Left = 40
      Top = 44
      Width = 54
      Height = 12
      Caption = #30331#24405#24080#21495':'
    end
    object Label2: TLabel
      Left = 40
      Top = 68
      Width = 54
      Height = 12
      Caption = #30331#24405#23494#30721':'
    end
    object ButtonLoginClose: TSpeedButton
      Left = 256
      Top = 8
      Width = 17
      Height = 25
      Caption = 'X'
      Flat = True
      OnClick = ButtonStartClick
    end
    object EditUserAccount: TEdit
      Left = 104
      Top = 40
      Width = 121
      Height = 20
      BevelKind = bkFlat
      BorderStyle = bsNone
      MaxLength = 10
      TabOrder = 0
      OnKeyPress = EditUserAccountKeyPress
    end
    object EditUserPassword: TEdit
      Left = 104
      Top = 64
      Width = 121
      Height = 20
      BevelKind = bkFlat
      BorderStyle = bsNone
      MaxLength = 10
      PasswordChar = '*'
      TabOrder = 1
      OnKeyPress = EditUserAccountKeyPress
    end
    object ButtonStart: TRzButton
      Left = 152
      Top = 96
      Caption = #30331#24405
      HotTrack = True
      TabOrder = 2
      OnClick = ButtonStartClick
      OnKeyPress = EditUserAccountKeyPress
    end
    object ButtonNewAccount: TRzButton
      Left = 72
      Top = 96
      Caption = #26032#24314#24080#21495
      HotTrack = True
      TabOrder = 3
      OnClick = ButtonStartClick
    end
    object GroupBox7: TGroupBox
      Left = 16
      Top = 128
      Width = 257
      Height = 49
      Caption = #33258#21160#30331#24405
      TabOrder = 4
      object CheckBoxAutoLogin: TCheckBox
        Left = 16
        Top = 16
        Width = 73
        Height = 17
        Caption = #33258#21160#30331#24405
        Checked = True
        State = cbChecked
        TabOrder = 0
        OnClick = CheckBoxAutoLoginClick
      end
      object ButtonChr1: TRadioButton
        Left = 96
        Top = 16
        Width = 65
        Height = 17
        Caption = #35282#33394#19968
        Checked = True
        TabOrder = 1
        TabStop = True
        OnClick = CheckBoxAutoLoginClick
      end
      object ButtonChr2: TRadioButton
        Left = 176
        Top = 16
        Width = 65
        Height = 17
        Caption = #35282#33394#20108
        TabOrder = 2
        OnClick = CheckBoxAutoLoginClick
      end
    end
  end
  object PanelMessageDlg: TPanel
    Left = 0
    Top = 48
    Width = 353
    Height = 153
    Color = clOlive
    TabOrder = 5
    Visible = False
    OnMouseDown = PanelUserLoginMouseDown
    object MsgBoxClose: TSpeedButton
      Left = 328
      Top = 8
      Width = 17
      Height = 25
      Caption = 'X'
      Flat = True
      OnClick = MsgBoxOKClick
    end
    object MsgBoxLabel: TLabel
      Left = 40
      Top = 28
      Width = 281
      Height = 61
      AutoSize = False
    end
    object MsgBoxOK: TRzButton
      Left = 24
      Top = 112
      Caption = #30830#23450
      HotTrack = True
      TabOrder = 0
      OnClick = MsgBoxOKClick
    end
    object MsgBoxCancel: TRzButton
      Left = 104
      Top = 112
      Caption = #21462#28040
      HotTrack = True
      TabOrder = 1
      OnClick = MsgBoxOKClick
    end
    object MsgBoxYes: TRzButton
      Left = 184
      Top = 112
      Caption = #26159
      HotTrack = True
      TabOrder = 2
      OnClick = MsgBoxOKClick
    end
    object MsgBoxNo: TRzButton
      Left = 262
      Top = 112
      Caption = #21542
      HotTrack = True
      TabOrder = 3
      OnClick = MsgBoxOKClick
    end
  end
  object MainMenu1: TMainMenu
    Left = 752
    object MENU_CONTROL: TMenuItem
      Caption = #25511#21046'(&C)'
      object MENU_CONTROL_EXIT: TMenuItem
        Caption = #36864#20986'(&X)'
        OnClick = MENU_CONTROL_EXITClick
      end
    end
  end
  object TimerMain: TTimer
    Enabled = False
    Interval = 1
    OnTimer = TimerMainTimer
    Left = 720
  end
  object CSocket: TClientSocket
    Active = False
    ClientType = ctNonBlocking
    Port = 0
    OnLookup = CSocketLookup
    OnConnecting = CSocketConnecting
    OnConnect = CSocketConnect
    OnDisconnect = CSocketDisconnect
    OnRead = CSocketRead
    OnError = CSocketError
    Left = 688
  end
  object CmdTimer: TTimer
    Enabled = False
    OnTimer = CmdTimerTimer
    Left = 656
  end
  object SelChrWaitTimer: TTimer
    Enabled = False
    OnTimer = CmdTimerTimer
    Left = 624
  end
  object WaitMsgTimer: TTimer
    Enabled = False
    Interval = 1
    OnTimer = CmdTimerTimer
    Left = 592
  end
  object MinTimer: TTimer
    Enabled = False
    OnTimer = CmdTimerTimer
    Left = 560
  end
  object PopupMenu: TPopupMenu
    Left = 528
    object POPMENU_AUTOSCROLL: TMenuItem
      Caption = #33258#21160#28378#21160
      Checked = True
      OnClick = POPMENU_AUTOSCROLLClick
    end
  end
end
