program LfHotel;

uses
  Forms,
  C_Main in 'Program\C_Main.pas' {MainForm},
  C_Define in 'Program\C_Define.pas',
  C_HotelData in 'Program\C_HotelData.pas' {HotelData: TDataModule},
  C_Stand in 'Program\C_Stand.pas' {StandForm},
  C_Ygda in 'Program\C_Ygda.pas' {YgdaForm},
  C_Khda in 'Program\C_Khda.pas' {KhdaForm},
  C_Hmd in 'Program\C_Hmd.pas' {HmdForm},
  C_Xtdy in 'Program\C_Xtdy.pas' {XtdyForm},
  C_StandDb in 'Program\C_StandDb.pas' {StandDbForm},
  C_Select in 'Program\C_Select.pas' {SelectForm},
  C_YdxxSel in 'Program\C_YdxxSel.pas' {YdxxSelForm},
  C_Kfdy in 'Program\C_Kfdy.pas' {KfdyForm},
  C_Browse in 'Program\C_Browse.pas' {BrowseForm},
  C_KhdaSel in 'Program\C_KhdaSel.pas' {KhdaSelForm},
  C_Sysprint in 'Program\C_Sysprint.pas' {SysPrintForm},
  C_Xmdy in 'Program\C_Xmdy.pas' {XmdyForm},
  C_StdJd in 'Program\C_StdJd.pas' {StdJdForm},
  C_Nbjd in 'Program\C_Nbjd.pas' {NbjdForm},
  C_Xxxg in 'Program\C_Xxxg.pas' {XxxgForm},
  C_Wbjd in 'Program\C_Wbjd.pas' {WbjdForm},
  C_Tdjd in 'Program\C_Tdjd.pas' {TdjdForm},
  C_Mfjd in 'Program\C_Mfjd.pas' {MfjdForm},
  C_Sktf in 'Program\C_Sktf.pas' {SktfForm},
  C_Tdsel in 'Program\C_Tdsel.pas' {TdSelForm},
  C_Tdbd in 'Program\C_Tdbd.pas' {TdbdForm},
  C_Krcx in 'Program\C_Krcx.pas' {KrcxForm},
  C_Yksy in 'Program\C_Yksy.pas' {YksyForm},
  C_Sjz in 'Program\C_Sjz.pas' {SjzForm},
  C_Bjyj in 'Program\C_Bjyj.pas' {BjyjForm},
  C_Skjz in 'Program\C_Skjz.pas' {SkjzForm},
  C_Zd in 'Program\C_Zd.pas' {ZdForm},
  C_Tdtf in 'Program\C_Tdtf.pas' {TdtfForm},
  C_Tdjz in 'Program\C_Tdjz.pas' {TdjzForm},
  C_Tdzd in 'Program\C_Tdzd.pas' {TdzdForm},
  C_StdBrow in 'Program\C_StdBrow.pas' {StdBrowForm},
  C_Rsmx in 'Program\C_Rsmx.pas' {RsmxForm},
  C_Dqsh in 'Program\C_Dqsh.pas' {DqshForm},
  C_Yxjz in 'Program\C_Yxjz.pas' {YxjzForm},
  C_YxjzTd in 'Program\C_YxjzTd.pas' {YxjzTdForm},
  C_Yjsh in 'Program\C_Yjsh.pas' {YjshForm},
  C_Bgrbb in 'Program\C_Bgrbb.pas' {BgRbbForm},
  C_YskYj in 'Program\C_YskYj.pas' {YskyjForm},
  C_Khyszz in 'Program\C_Khyszz.pas' {KhyszzForm},
  C_Khxfmx in 'Program\C_Khxfmx.pas' {KhxfmxForm},
  C_Fjbg in 'Program\C_Fjbg.pas' {FjbgForm},
  C_FykJz in 'Program\C_FykJz.pas' {FykJzForm},
  C_Lkysk in 'Program\C_Lkysk.pas' {LkyskForm},
  C_Khjzmx in 'Program\C_Khjzmx.pas' {KhjzmxForm},
  C_Cwjs in 'Program\C_Cwjs.pas' {CwjsForm},
  C_CwjsBrow in 'Program\C_CwjsBrow.pas' {CwjsBrowForm},
  C_Lctj in 'Program\C_Lctj.pas' {LctjForm},
  C_Bqjtj in 'Program\C_Bqjtj.pas' {BqjTjForm},
  C_Yskzd in 'Program\C_Yskzd.pas' {YskZdForm},
  C_Wjzjz in 'Program\C_Wjzjz.pas' {WjzjzForm},
  C_Skyjbg in 'Program\C_Skyjbg.pas' {SkyjbgForm},
  C_Kfrbb in 'Program\C_Kfrbb.pas' {KfrbbForm},
  C_Jzfltj in 'Program\C_Jzfltj.pas' {JzfltjForm},
  C_Fykcx in 'Program\C_Fykcx.pas' {FykcxForm},
  C_Ldkrcx in 'Program\C_Ldkrcx.pas' {LdkrcxForm},
  C_Ftdh in 'Program\C_Ftdh.pas' {FtdhForm},
  C_Tdyfcx in 'Program\C_Tdyfcx.pas' {TdyfcxForm},
  C_Ftsm in 'Program\C_Ftsm.pas' {FtsmForm},
  C_Ydhc in 'Program\C_Ydhc.pas' {YdhcForm},
  C_Xtsz in 'Program\C_Xtsz.pas' {XtszForm},
  C_Ydcysk in 'Program\C_Ydcysk.pas' {YdcyskForm},
  C_Hcjs in 'Program\C_Hcjs.pas' {HcjsForm},
  C_Ydcytd in 'Program\C_Ydcytd.pas' {YdcytdForm},
  C_Ydkfsk in 'Program\C_Ydkfsk.pas' {YdkfskForm},
  C_Ydkftd in 'Program\C_Ydkftd.pas' {YdkftdForm},
  C_Krly in 'Program\C_Krly.pas' {KrlyForm},
  C_Lcsk in 'Program\C_Lcsk.pas' {LcskForm},
  C_Hbsk in 'Program\C_Hbsk.pas' {HbskForm},
  C_Ygkf in 'Program\C_Ygkf.pas' {YgkfForm},
  C_ChartPrint in 'Program\C_ChartPrint.pas' {ChartPrintForm},
  C_About in 'Program\C_About.pas' {AboutForm},
  C_Ydxx in 'Program\C_Ydxx.pas' {YdxxForm},
  C_CardXf in 'Program\C_CardXf.pas' {CardXfForm},
  IcCardDefine in 'Program\IcCardDefine.pas',
  drv_unit in 'Program\drv_unit.pas',
  C_Klsz in 'Program\C_Klsz.pas' {KlszForm},
  C_Password in 'Program\C_Password.pas' {PasswordForm},
  C_Ygqx in 'Program\C_Ygqx.pas' {YgqxForm},
  C_Ydsm in 'Program\C_Ydsm.pas' {YdsmForm},
  C_DhfBrow in 'Program\C_DhfBrow.pas' {DhfBrowForm},
  C_Skqx in 'Program\C_Skqx.pas' {SkqxForm},
  C_BakData in 'Program\C_BakData.pas' {BakDataForm},
  C_Zdcxtd in 'Program\C_Zdcxtd.pas' {ZdcxTdForm},
  C_Zdcx in 'Program\C_Zdcx.pas' {ZdcxForm},
  C_Dtbqj in 'Program\C_Dtbqj.pas' {DtbqjForm},
  C_Wait in 'Program\C_Wait.pas' {WaitForm},
  C_Splash in 'Program\C_Splash.pas' {SplashForm},
  C_Ydcycx in 'Program\C_Ydcycx.pas' {YdcycxForm},
  C_Ydkfcx in 'Program\C_Ydkfcx.pas' {YdkfcxForm},
  C_XfxmBrow in 'Program\C_XfxmBrow.pas' {XfxmBrowForm},
  C_Ydhccx in 'Program\C_Ydhccx.pas' {YdhccxForm},
  C_SelectDir in 'Program\C_SelectDir.pas' {SelectDirForm},
  C_Ygjz in 'Program\C_Ygjz.pas' {YgjzForm},
  C_YdcyskPrint in 'Program\C_YdcyskPrint.pas' {YdcyskPrintForm},
  C_Yszz in 'Program\C_Yszz.pas' {YszzForm},
  C_KfrbbPrn in 'Program\C_KfrbbPrn.pas' {KfrbbPrnForm},
  C_BgrbbPrn in 'Program\C_BgrbbPrn.pas' {BgrbbPrnForm},
  C_Ysklr in 'Program\C_Ysklr.pas' {YsklrForm},
  C_Zdmx in 'Program\C_Zdmx.pas' {ZdmxForm},
  C_Fjmx in 'Program\C_Fjmx.pas' {FjmxForm},
  C_Dqshmx in 'Program\C_Dqshmx.pas' {DqshmxForm},
  C_YdhcPrint in 'Program\C_YdhcPrint.pas' {YdhcPrintForm},
  C_FjhbPrint in 'Program\C_FjhbPrint.pas' {FjhbPrintForm},
  C_YskPrint in 'Program\C_YskPrint.pas' {YskPrintForm},
  C_Yjcx in 'Program\C_Yjcx.pas' {YjcxForm},
  C_Krxx in 'Program\C_Krxx.pas' {KrxxForm},
  C_Yskcx in 'Program\C_Yskcx.pas' {YskcxForm},
  C_Dhfcx in 'Program\C_Dhfcx.pas' {DhfCxForm},
  C_Dhhm in 'Program\C_Dhhm.pas' {DhhmForm},
  C_YdcytdPrint in 'Program\C_YdcytdPrint.pas' {YdcytdPrintForm},
  C_PrintDlg in 'Program\C_PrintDlg.pas' {PrintDlgForm},
  C_Preview in 'Program\C_Preview.pas' {PreviewForm},
  C_Zdlrcx in 'Program\C_Zdlrcx.pas' {ZdlrcxForm},
  C_Fykjzcx in 'Program\C_Fykjzcx.pas' {FykjzcxForm},
  C_Ldkr in 'Program\C_Ldkr.pas' {LdkrForm},
  C_Hcjscx in 'Program\C_Hcjscx.pas' {HcjscxForm},
  C_LybBrow in 'Program\C_LybBrow.pas' {LybBrowForm},
  C_LybEdit in 'Program\C_LybEdit.pas' {LybEditForm};

{$R *.res}

begin
  Application.Initialize;
  Application.Title := '立方酒店管理系统';
  SplashForm := TSplashForm.Create(Application);
  SplashForm.Show;
  SplashForm.Update;
  Application.CreateForm(THotelData, HotelData);
  Application.CreateForm(TMainForm, MainForm);
  Application.CreateForm(TFtdhForm, FtdhForm);
  Application.CreateForm(TPreviewForm, PreviewForm);
  SplashForm.Hide;
  SplashForm.Free;
  Application.Run;
end.
